iRRAM: iRRAM::INTERVAL Class Reference
iRRAM::INTERVAL Class Reference
Data Types
#include <INTERVAL.h>
Public Member Functions
INTERVAL ()
INTERVAL (const INTERVAL &x)=default
INTERVAL (INTERVAL &&x) noexcept=default
INTERVAL (const REAL &x)
INTERVAL (const REAL &x, const REAL &y)
INTERVAL (REAL l, REAL r, bool)
INTERVAL & operator= (const INTERVAL &x)=default
INTERVAL & operator= (INTERVAL &&x) noexcept=default
Public Attributes
REAL low
REAL upp
Friends
INTERVAL operator+ (INTERVAL x, const INTERVAL &y)
INTERVAL & operator+= (INTERVAL &x, const INTERVAL &y)
INTERVAL operator- (INTERVAL x, const INTERVAL &y)
INTERVAL & operator-= (INTERVAL &x, const INTERVAL &y)
INTERVAL operator- (const INTERVAL &x)
INTERVAL operator* (const INTERVAL &x, const INTERVAL &y)
INTERVAL & operator*= (INTERVAL &x, const INTERVAL &y)
INTERVAL operator/ (const INTERVAL &x, const INTERVAL &y)
INTERVAL & operator/= (INTERVAL &x, const INTERVAL &y)
REAL wid (const INTERVAL &x)
REAL inf (const INTERVAL &x)
REAL sup (const INTERVAL &x)
REAL mid (const INTERVAL &x)
REAL mag (const INTERVAL &x)
REAL mig (const INTERVAL &x)
LAZY_BOOLEAN superset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN proper_superset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN subset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN proper_subset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN in_interior (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN disjoint (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN in (const REAL &x, const INTERVAL &y)
INTERVAL interval_hull (const INTERVAL &x, const INTERVAL &y)
INTERVAL intersect (const INTERVAL &x, const INTERVAL &y)
INTERVAL fabs (const INTERVAL &x)
INTERVAL power (const INTERVAL &x, int n)
INTERVAL square (const INTERVAL &x)
INTERVAL exp (const INTERVAL &x)
INTERVAL log (const INTERVAL &x)
INTERVAL sin (const INTERVAL &x)
INTERVAL cos (const INTERVAL &x)
INTERVAL tan (const INTERVAL &x)
INTERVAL asin (const INTERVAL &x)
INTERVAL acos (const INTERVAL &x)
INTERVAL atan (const INTERVAL &x)
Detailed Description
Definition at line 40 of file INTERVAL.h.
Constructor & Destructor Documentation
INTERVAL() [1/6]
iRRAM::INTERVAL::INTERVAL ()
Definition at line 30 of file INTERVAL.cc.
Referenced by iRRAM::acos(), iRRAM::asin(), iRRAM::atan(), iRRAM::cos(), iRRAM::exp(), iRRAM::fabs(), iRRAM::intersect(), INTERVAL(), iRRAM::interval_hull(), iRRAM::log(), iRRAM::operator*(), iRRAM::operator-(), iRRAM::operator/(), iRRAM::power(), iRRAM::sin(), iRRAM::square(), and iRRAM::tan().
INTERVAL() [2/6]
iRRAM::INTERVAL::INTERVAL (const INTERVAL & x) default
INTERVAL() [3/6]
iRRAM::INTERVAL::INTERVAL (INTERVAL && x) default noexcept
INTERVAL() [4/6]
iRRAM::INTERVAL::INTERVAL (const REAL & x) inline
Definition at line 52 of file INTERVAL.h.
References INTERVAL().
INTERVAL() [5/6]
iRRAM::INTERVAL::INTERVAL (const REAL & x, const REAL & y)
Definition at line 32 of file INTERVAL.cc.
INTERVAL() [6/6]
iRRAM::INTERVAL::INTERVAL (REAL l, REAL r, bool) inline
Definition at line 58 of file INTERVAL.h.
References operator=().
Member Function Documentation
operator=() [1/2]
INTERVAL& iRRAM::INTERVAL::operator= (const INTERVAL & x) default
Referenced by INTERVAL().
operator=() [2/2]
INTERVAL& iRRAM::INTERVAL::operator= (INTERVAL && x) default noexcept
Friends And Related Function Documentation
acos
INTERVAL acos (const INTERVAL & x) friend
Definition at line 301 of file INTERVAL.cc.
Referenced by iRRAM::acos().
asin
INTERVAL asin (const INTERVAL & x) friend
Definition at line 296 of file INTERVAL.cc.
Referenced by iRRAM::asin().
atan
INTERVAL atan (const INTERVAL & x) friend
Definition at line 306 of file INTERVAL.cc.
Referenced by iRRAM::atan().
cos
INTERVAL cos (const INTERVAL & x) friend
Definition at line 221 of file INTERVAL.cc.
Referenced by iRRAM::cos().
disjoint
LAZY_BOOLEAN disjoint (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 329 of file INTERVAL.cc.
exp
INTERVAL exp (const INTERVAL & x) friend
Definition at line 148 of file INTERVAL.cc.
Referenced by iRRAM::exp().
fabs
INTERVAL fabs (const INTERVAL & x) friend
Definition at line 126 of file INTERVAL.cc.
in
LAZY_BOOLEAN in (const REAL & x, const INTERVAL & y) friend
Definition at line 332 of file INTERVAL.cc.
in_interior
LAZY_BOOLEAN in_interior (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 326 of file INTERVAL.cc.
inf
REAL inf (const INTERVAL & x) friend
Definition at line 106 of file INTERVAL.cc.
intersect
INTERVAL intersect (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 338 of file INTERVAL.cc.
interval_hull
INTERVAL interval_hull (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 335 of file INTERVAL.cc.
log
INTERVAL log (const INTERVAL & x) friend
Definition at line 153 of file INTERVAL.cc.
Referenced by iRRAM::log().
mag
REAL mag (const INTERVAL & x) friend
Definition at line 118 of file INTERVAL.cc.
mid
REAL mid (const INTERVAL & x) friend
Definition at line 114 of file INTERVAL.cc.
mig
REAL mig (const INTERVAL & x) friend
Definition at line 122 of file INTERVAL.cc.
operator*
INTERVAL operator* (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 63 of file INTERVAL.cc.
operator*=
INTERVAL& operator*= (INTERVAL & x, const INTERVAL & y) friend
Definition at line 73 of file INTERVAL.h.
operator+
INTERVAL operator+ (INTERVAL x, const INTERVAL & y) friend
Definition at line 65 of file INTERVAL.h.
operator+=
INTERVAL& operator+= (INTERVAL & x, const INTERVAL & y) friend
Definition at line 35 of file INTERVAL.cc.
operator- [1/2]
INTERVAL operator- (INTERVAL x, const INTERVAL & y) friend
Definition at line 68 of file INTERVAL.h.
operator- [2/2]
INTERVAL operator- (const INTERVAL & x) friend
Definition at line 49 of file INTERVAL.cc.
operator-=
INTERVAL& operator-= (INTERVAL & x, const INTERVAL & y) friend
Definition at line 42 of file INTERVAL.cc.
operator/
INTERVAL operator/ (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 94 of file INTERVAL.cc.
operator/=
INTERVAL& operator/= (INTERVAL & x, const INTERVAL & y) friend
Definition at line 76 of file INTERVAL.h.
power
INTERVAL power (const INTERVAL & x, int n) friend
Definition at line 136 of file INTERVAL.cc.
Referenced by iRRAM::power().
proper_subset
LAZY_BOOLEAN proper_subset (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 323 of file INTERVAL.cc.
proper_superset
LAZY_BOOLEAN proper_superset (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 317 of file INTERVAL.cc.
sin
INTERVAL sin (const INTERVAL & x) friend
Definition at line 158 of file INTERVAL.cc.
Referenced by iRRAM::sin().
square
INTERVAL square (const INTERVAL & x) friend
Definition at line 131 of file INTERVAL.cc.
Referenced by iRRAM::power(), and iRRAM::square().
subset
LAZY_BOOLEAN subset (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 320 of file INTERVAL.cc.
sup
REAL sup (const INTERVAL & x) friend
Definition at line 110 of file INTERVAL.cc.
superset
LAZY_BOOLEAN superset (const INTERVAL & x, const INTERVAL & y) friend
Definition at line 311 of file INTERVAL.cc.
Referenced by iRRAM::in_interior(), iRRAM::proper_subset(), iRRAM::proper_superset(), and iRRAM::subset().
tan
INTERVAL tan (const INTERVAL & x) friend
Definition at line 285 of file INTERVAL.cc.
Referenced by iRRAM::tan().
wid
REAL wid (const INTERVAL & x) friend
Definition at line 102 of file INTERVAL.cc.
Member Data Documentation
low
REAL iRRAM::INTERVAL::low
Definition at line 119 of file INTERVAL.h.
Referenced by iRRAM::acos(), iRRAM::asin(), iRRAM::atan(), iRRAM::cos(), iRRAM::disjoint(), iRRAM::exp(), iRRAM::fabs(), iRRAM::in(), iRRAM::inf(), iRRAM::intersect(), iRRAM::interval_hull(), iRRAM::log(), iRRAM::mag(), iRRAM::mid(), iRRAM::mig(), iRRAM::operator*(), iRRAM::operator+=(), iRRAM::operator-(), iRRAM::operator-=(), iRRAM::operator/(), iRRAM::power(), iRRAM::sin(), iRRAM::square(), iRRAM::superset(), iRRAM::tan(), and iRRAM::wid().
upp
REAL iRRAM::INTERVAL::upp
Definition at line 120 of file INTERVAL.h.
Referenced by iRRAM::acos(), iRRAM::asin(), iRRAM::atan(), iRRAM::cos(), iRRAM::disjoint(), iRRAM::exp(), iRRAM::fabs(), iRRAM::in(), iRRAM::intersect(), iRRAM::interval_hull(), iRRAM::log(), iRRAM::mag(), iRRAM::mid(), iRRAM::mig(), iRRAM::operator*(), iRRAM::operator+=(), iRRAM::operator-(), iRRAM::operator-=(), iRRAM::operator/(), iRRAM::power(), iRRAM::sin(), iRRAM::square(), iRRAM::sup(), iRRAM::superset(), iRRAM::tan(), and iRRAM::wid().
The documentation for this class was generated from the following files:
include/iRRAM/INTERVAL.h
src/INTERVAL.cc