iRRAM: iRRAM::REALMATRIX Class Reference
iRRAM::REALMATRIX Class Reference
Data Types
#include <REALMATRIX.h>
Public Member Functions
REALMATRIX (unsigned int rows, unsigned int columns)
REALMATRIX ()
REALMATRIX (const REALMATRIX &y)
REALMATRIX & operator= (const REALMATRIX &y)
~REALMATRIX ()
REAL & operator() (unsigned int row, unsigned int column) const
REAL & element (unsigned int row, unsigned int column) const
void adderror (sizetype error)
void seterror (sizetype error)
void geterror (sizetype &error) const
sizetype geterror () const
Public Attributes
REAL * values
unsigned int maxrow
unsigned int maxcolumn
Friends
REALMATRIX operator+ (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator- (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator* (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator/ (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator* (const REALMATRIX &x, const REAL &y)
REALMATRIX operator* (const REAL &y, const REALMATRIX &x)
REALMATRIX operator/ (const REALMATRIX &x, const REAL &y)
unsigned int rows (const REALMATRIX &x)
unsigned int columns (const REALMATRIX &x)
int bound (const REALMATRIX &x, const int k)
REALMATRIX eye (unsigned int rows)
REALMATRIX zeroes (unsigned int rows, unsigned int columns)
REALMATRIX ones (unsigned int rows, unsigned int columns)
REAL maxnorm (const REALMATRIX &x)
REAL rowsumnorm (const REALMATRIX &x)
REAL colsumnorm (const REALMATRIX &x)
REALMATRIX solve (REALMATRIX &lside, REALMATRIX &rside, int use_pivot)
REALMATRIX limit_lip (REALMATRIX f(int, const REALMATRIX &), int lip, bool on_domain(const REALMATRIX &), const REALMATRIX &x)
Related Functions
(Note that these are not member functions.)
sizetype geterror (const REALMATRIX &r)
void seterror (REALMATRIX &r, const sizetype &err)
Detailed Description
Definition at line 35 of file REALMATRIX.h.
Constructor & Destructor Documentation
iRRAM::REALMATRIX::REALMATRIX (unsigned int rows, unsigned int columns)
Definition at line 36 of file REALMATRIX.cc.
References columns, maxcolumn, maxrow, rows, and values.
iRRAM::REALMATRIX::REALMATRIX ()
Definition at line 189 of file REALMATRIX.cc.
References maxcolumn, maxrow, and values.
iRRAM::REALMATRIX::REALMATRIX (const REALMATRIX & y)
Definition at line 193 of file REALMATRIX.cc.
References maxcolumn, maxrow, iRRAM::size(), and values.
iRRAM::REALMATRIX::~REALMATRIX ()
Definition at line 184 of file REALMATRIX.cc.
References values.
Member Function Documentation
void iRRAM::REALMATRIX::adderror (sizetype error)
Definition at line 244 of file REALMATRIX.cc.
References ELEMENT.
Referenced by iRRAM::limit_lip().
REAL & iRRAM::REALMATRIX::element (unsigned int row, unsigned int column) const
Definition at line 200 of file REALMATRIX.cc.
References maxcolumn, maxrow, and values.
void iRRAM::REALMATRIX::geterror (sizetype & error) const
Definition at line 258 of file REALMATRIX.cc.
References ELEMENT, and iRRAM::max().
Referenced by geterror(), and iRRAM::limit_lip().
sizetype iRRAM::REALMATRIX::geterror () const inline
Definition at line 120 of file REALMATRIX.h.
References geterror().
Referenced by geterror().
REAL & iRRAM::REALMATRIX::operator() (unsigned int row, unsigned int column) const
Definition at line 209 of file REALMATRIX.cc.
References maxcolumn, maxrow, and values.
REALMATRIX & iRRAM::REALMATRIX::operator= (const REALMATRIX & y)
Definition at line 74 of file REALMATRIX.cc.
References maxcolumn, maxrow, iRRAM::size(), and values.
void iRRAM::REALMATRIX::seterror (sizetype error)
Definition at line 251 of file REALMATRIX.cc.
References ELEMENT.
Referenced by iRRAM::limit_lip(), and seterror().
Friends And Related Function Documentation
int bound (const REALMATRIX & x, const int k) friend
Definition at line 237 of file REALMATRIX.cc.
Referenced by iRRAM::bound(), iRRAM::colsumnorm(), and iRRAM::exp().
REAL colsumnorm (const REALMATRIX & x) friend
Definition at line 289 of file REALMATRIX.cc.
Referenced by seterror().
unsigned int columns (const REALMATRIX & x) friend
Definition at line 84 of file REALMATRIX.h.
Referenced by iRRAM::colsumnorm(), iRRAM::ones(), REALMATRIX(), seterror(), iRRAM::steady_state(), and iRRAM::zeroes().
REALMATRIX eye (unsigned int rows) friend
Definition at line 48 of file REALMATRIX.cc.
Referenced by iRRAM::colsumnorm(), and seterror().
sizetype geterror (const REALMATRIX & r) related
Definition at line 124 of file REALMATRIX.h.
References geterror().
REALMATRIX limit_lip (REALMATRIX fint, const REALMATRIX &, int lip, bool on_domainconst REALMATRIX &, const REALMATRIX & x) friend
Referenced by iRRAM::exp(), and seterror().
REAL maxnorm (const REALMATRIX & x) friend
Definition at line 271 of file REALMATRIX.cc.
Referenced by seterror().
REALMATRIX ones (unsigned int rows, unsigned int columns) friend
Definition at line 64 of file REALMATRIX.cc.
Referenced by seterror().
REALMATRIX operator* (const REALMATRIX & x, const REALMATRIX & y) friend
Definition at line 110 of file REALMATRIX.cc.
REALMATRIX operator* (const REALMATRIX & x, const REAL & y) friend
Definition at line 219 of file REALMATRIX.cc.
REALMATRIX operator* (const REAL & y, const REALMATRIX & x) friend
Definition at line 73 of file REALMATRIX.h.
REALMATRIX operator+ (const REALMATRIX & x, const REALMATRIX & y) friend
Definition at line 86 of file REALMATRIX.cc.
REALMATRIX operator- (const REALMATRIX & x, const REALMATRIX & y) friend
Definition at line 98 of file REALMATRIX.cc.
REALMATRIX operator/ (const REALMATRIX & x, const REALMATRIX & y) friend
Definition at line 126 of file REALMATRIX.cc.
REALMATRIX operator/ (const REALMATRIX & x, const REAL & y) friend
Definition at line 228 of file REALMATRIX.cc.
unsigned int rows (const REALMATRIX & x) friend
Definition at line 82 of file REALMATRIX.h.
Referenced by iRRAM::colsumnorm(), iRRAM::eye(), iRRAM::ones(), REALMATRIX(), seterror(), iRRAM::steady_state(), and iRRAM::zeroes().
REAL rowsumnorm (const REALMATRIX & x) friend
Definition at line 278 of file REALMATRIX.cc.
Referenced by seterror().
void seterror (REALMATRIX & r, const sizetype & err) related
Definition at line 126 of file REALMATRIX.h.
References colsumnorm, columns, iRRAM::equilib(), iRRAM::equilib_del(), iRRAM::exp(), eye, limit_lip, maxnorm, ones, rows, rowsumnorm, seterror(), solve, iRRAM::steady_state(), and zeroes.
REALMATRIX solve (REALMATRIX & lside, REALMATRIX & rside, int use_pivot) friend
Definition at line 132 of file REALMATRIX.cc.
Referenced by iRRAM::operator/(), and seterror().
REALMATRIX zeroes (unsigned int rows, unsigned int columns) friend
Definition at line 54 of file REALMATRIX.cc.
Referenced by iRRAM::equilib_del(), and seterror().
Member Data Documentation
unsigned int iRRAM::REALMATRIX::maxcolumn
Definition at line 116 of file REALMATRIX.h.
Referenced by iRRAM::bound(), iRRAM::colsumnorm(), element(), iRRAM::maxnorm(), operator()(), iRRAM::operator*(), iRRAM::operator+(), iRRAM::operator-(), iRRAM::operator/(), operator=(), REALMATRIX(), iRRAM::rowsumnorm(), and iRRAM::solve().
unsigned int iRRAM::REALMATRIX::maxrow
Definition at line 116 of file REALMATRIX.h.
Referenced by iRRAM::bound(), iRRAM::colsumnorm(), element(), iRRAM::maxnorm(), operator()(), iRRAM::operator*(), iRRAM::operator+(), iRRAM::operator-(), iRRAM::operator/(), operator=(), REALMATRIX(), iRRAM::rowsumnorm(), and iRRAM::solve().
REAL* iRRAM::REALMATRIX::values
Definition at line 115 of file REALMATRIX.h.
Referenced by element(), iRRAM::maxnorm(), operator()(), iRRAM::operator+(), iRRAM::operator-(), operator=(), REALMATRIX(), and ~REALMATRIX().
The documentation for this class was generated from the following files:
include/iRRAM/REALMATRIX.h
src/REALMATRIX.cc