iRRAM: iRRAM::DYADIC Class Reference
iRRAM::DYADIC Class Reference
Data Types
#include <DYADIC.h>
Public Member Functions
DYADIC ()
DYADIC (const int i)
DYADIC (const double y)
DYADIC (const INTEGER &y)
DYADIC (const DYADIC &y)
DYADIC (DYADIC &&y) noexcept
DYADIC & operator= (const DYADIC &y)
DYADIC & operator= (DYADIC &&y) noexcept
~DYADIC ()
INTEGER as_INTEGER () const
Static Public Member Functions
static int getprec ()
Public Attributes
MP_type value
Friends
class REAL
class INTEGER
class RATIONAL
DYADIC ADD (const DYADIC &x, const DYADIC &y, int p)
DYADIC SUB (const DYADIC &x, const DYADIC &y, int p)
DYADIC MULT (const DYADIC &x, const DYADIC &y, int p)
DYADIC DIV (const DYADIC &x, const DYADIC &y, int p)
DYADIC operator+ (const DYADIC &x, const DYADIC &y)
DYADIC operator- (const DYADIC &x, const DYADIC &y)
DYADIC operator- (const DYADIC &x)
DYADIC operator* (const DYADIC &x, const DYADIC &y)
DYADIC operator/ (const DYADIC &x, const DYADIC &y)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator+ (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator+ (const B &b, const A &a)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator- (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator- (const B &b, const A &a)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator* (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator* (const B &b, const A &a)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator/ (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< DYADIC, A, B > operator/ (const B &b, const A &a)
bool operator< (const DYADIC &x, const DYADIC &y)
bool operator> (const DYADIC &x, const DYADIC &y)
bool operator<= (const DYADIC &x, const DYADIC &y)
bool operator>= (const DYADIC &x, const DYADIC &y)
bool operator== (const DYADIC &x, const DYADIC &y)
bool operator!= (const DYADIC &x, const DYADIC &y)
std::string swrite (const DYADIC &x, const int w)
int size (const DYADIC &x)
DYADIC abs (const DYADIC &x)
DYADIC scale (const DYADIC &x, const int k)
DYADIC approx (const REAL &x, const int p)
Computes a dyadic approximation to x that is accurate to 2^p.
Detailed Description
Definition at line 33 of file DYADIC.h.
Constructor & Destructor Documentation
iRRAM::DYADIC::DYADIC ()
Definition at line 39 of file DYADIC.cc.
References MP_init, MP_int_to_mp, MP_type, and value.
Referenced by getprec(), and iRRAM::scale().
iRRAM::DYADIC::DYADIC (const int i)
Definition at line 46 of file DYADIC.cc.
References MP_init, MP_int_to_mp, and value.
iRRAM::DYADIC::DYADIC (const double y)
Definition at line 58 of file DYADIC.cc.
References MP_double_to_mp, MP_init, and value.
iRRAM::DYADIC::DYADIC (const INTEGER & y)
Definition at line 50 of file DYADIC.cc.
References MP_init, MP_INTEGER_to_mp, and value.
iRRAM::DYADIC::DYADIC (const DYADIC & y)
Definition at line 54 of file DYADIC.cc.
References MP_duplicate_w_init, and value.
iRRAM::DYADIC::DYADIC (DYADIC && y) inline noexcept
Definition at line 45 of file DYADIC.h.
References operator=(), and value.
iRRAM::DYADIC::~DYADIC ()
Definition at line 62 of file DYADIC.cc.
References MP_clear, and value.
Referenced by operator=().
Member Function Documentation
INTEGER iRRAM::DYADIC::as_INTEGER () const
Definition at line 145 of file DYADIC.cc.
References MP_mp_to_INTEGER, and value.
static int iRRAM::DYADIC::getprec () inline static
Definition at line 36 of file DYADIC.h.
References DYADIC(), iRRAM::state_t::DYADIC_precision, and iRRAM::state.
Referenced by iRRAM::REAL::as_DYADIC().
DYADIC & iRRAM::DYADIC::operator= (const DYADIC & y)
Definition at line 104 of file DYADIC.cc.
References MP_duplicate_wo_init, and value.
Referenced by DYADIC().
DYADIC& iRRAM::DYADIC::operator= (DYADIC && y) inline noexcept
Definition at line 50 of file DYADIC.h.
References ADD, DIV, MULT, SUB, iRRAM::swap(), value, and ~DYADIC().
Friends And Related Function Documentation
DYADIC abs (const DYADIC & x) friend
Definition at line 138 of file DYADIC.cc.
DYADIC ADD (const DYADIC & x, const DYADIC & y, int p) friend
Definition at line 66 of file DYADIC.cc.
Referenced by operator=().
DYADIC approx (const REAL & x, const int p) friend
Computes a dyadic approximation to x that is accurate to 2^p.
This is a multi-valued function.
Reiteration is used to ensure \(x_\varepsilon\leq2^{p+1}\). The computed value at least as precise as \(x_c\) rounded to a multiple of \(2^{p-1}\).
Parameters
x the real number to approximate
p accuracy
Returns
a dyadic approximation q that satisfies |x-q|<2^p.
Exceptions
Iteration when \(2^{p+1}<x_\varepsilon\)
See also
REITERATE
Definition at line 605 of file REALS.cc.
DYADIC DIV (const DYADIC & x, const DYADIC & y, int p) friend
Definition at line 87 of file DYADIC.cc.
Referenced by operator=().
friend class INTEGER friend
Definition at line 103 of file DYADIC.h.
DYADIC MULT (const DYADIC & x, const DYADIC & y, int p) friend
Definition at line 80 of file DYADIC.cc.
Referenced by operator=().
bool operator!= (const DYADIC & x, const DYADIC & y) friend
Definition at line 120 of file DYADIC.cc.
DYADIC operator* (const DYADIC & x, const DYADIC & y) friend
Definition at line 66 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator* (const A & a, const B & b) friend
Definition at line 75 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator* (const B & b, const A & a) friend
Definition at line 76 of file DYADIC.h.
DYADIC operator+ (const DYADIC & x, const DYADIC & y) friend
Definition at line 63 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator+ (const A & a, const B & b) friend
Definition at line 69 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator+ (const B & b, const A & a) friend
Definition at line 70 of file DYADIC.h.
DYADIC operator- (const DYADIC & x, const DYADIC & y) friend
Definition at line 64 of file DYADIC.h.
DYADIC operator- (const DYADIC & x) friend
Definition at line 65 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator- (const A & a, const B & b) friend
Definition at line 72 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator- (const B & b, const A & a) friend
Definition at line 73 of file DYADIC.h.
DYADIC operator/ (const DYADIC & x, const DYADIC & y) friend
Definition at line 67 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator/ (const A & a, const B & b) friend
Definition at line 78 of file DYADIC.h.
template<typename A , typename B > enable_if_compat<DYADIC,A,B> operator/ (const B & b, const A & a) friend
Definition at line 79 of file DYADIC.h.
bool operator< (const DYADIC & x, const DYADIC & y) friend
Definition at line 109 of file DYADIC.cc.
bool operator<= (const DYADIC & x, const DYADIC & y) friend
Definition at line 114 of file DYADIC.cc.
bool operator== (const DYADIC & x, const DYADIC & y) friend
Definition at line 116 of file DYADIC.cc.
bool operator> (const DYADIC & x, const DYADIC & y) friend
Definition at line 113 of file DYADIC.cc.
bool operator>= (const DYADIC & x, const DYADIC & y) friend
Definition at line 115 of file DYADIC.cc.
friend class RATIONAL friend
Definition at line 104 of file DYADIC.h.
friend class REAL friend
Definition at line 102 of file DYADIC.h.
DYADIC scale (const DYADIC & x, const int k) friend
Definition at line 96 of file DYADIC.cc.
int size (const DYADIC & x) friend
Definition at line 131 of file DYADIC.cc.
DYADIC SUB (const DYADIC & x, const DYADIC & y, int p) friend
Definition at line 73 of file DYADIC.cc.
Referenced by operator=().
std::string swrite (const DYADIC & x, const int w) friend
Definition at line 122 of file DYADIC.cc.
Member Data Documentation
MP_type iRRAM::DYADIC::value
Definition at line 112 of file DYADIC.h.
Referenced by iRRAM::abs(), iRRAM::ADD(), iRRAM::REAL::as_double(), as_INTEGER(), iRRAM::DIV(), DYADIC(), mpfr_wrapper(), iRRAM::MULT(), iRRAM::operator<(), operator=(), iRRAM::operator==(), iRRAM::REAL::REAL(), iRRAM::root(), iRRAM::scale(), iRRAM::size(), iRRAM::SUB(), iRRAM::swrite(), iRRAM::REAL::to_formal_ball(), and ~DYADIC().
The documentation for this class was generated from the following files:
include/iRRAM/DYADIC.h
src/DYADIC.cc