iRRAM: iRRAM::COMPLEX Class Reference
iRRAM::COMPLEX Class Reference
Data Types
#include <COMPLEX.h>
Public Member Functions
COMPLEX (REAL real_part=0, REAL imag_part=0)
void adderror (sizetype error)
void seterror (sizetype error)
void geterror (sizetype &error) const
sizetype geterror () const
Public Attributes
REAL _real
REAL _imag
Friends
COMPLEX operator+ (const COMPLEX &x, const COMPLEX &y)
COMPLEX operator- (const COMPLEX &x, const COMPLEX &y)
COMPLEX operator- (const COMPLEX &x)
COMPLEX operator* (const COMPLEX &x, const COMPLEX &y)
COMPLEX operator/ (const COMPLEX &x, const COMPLEX &y)
REAL real (const COMPLEX &z)
REAL imag (const COMPLEX &z)
REAL abs (const COMPLEX &z)
REAL arg (const COMPLEX &z)
Related Functions
(Note that these are not member functions.)
sizetype geterror (const COMPLEX &r)
void seterror (COMPLEX &r, const sizetype &err)
Detailed Description
Definition at line 35 of file COMPLEX.h.
Constructor & Destructor Documentation
COMPLEX()
iRRAM::COMPLEX::COMPLEX (REAL real_part = 0, REAL imag_part = 0)
Definition at line 31 of file COMPLEX.cc.
Referenced by iRRAM::abs(), iRRAM::acos(), iRRAM::acosec(), iRRAM::acosech(), iRRAM::acosh(), iRRAM::acotan(), iRRAM::acoth(), iRRAM::arg(), iRRAM::asec(), iRRAM::asech(), iRRAM::asin(), iRRAM::asinh(), iRRAM::atan(), iRRAM::atanh(), iRRAM::cos(), iRRAM::cosec(), iRRAM::cosech(), iRRAM::cosh(), iRRAM::cotan(), iRRAM::csqrt(), iRRAM::exp(), iRRAM::log(), iRRAM::operator*(), iRRAM::operator+(), iRRAM::operator-(), iRRAM::operator/(), iRRAM::sec(), iRRAM::sech(), iRRAM::sin(), and iRRAM::sinh().
Member Function Documentation
adderror()
void iRRAM::COMPLEX::adderror (sizetype error)
Definition at line 35 of file COMPLEX.cc.
References _imag, _real, and iRRAM::REAL::adderror().
geterror() [1/2]
void iRRAM::COMPLEX::geterror (sizetype & error) const
Definition at line 47 of file COMPLEX.cc.
References _imag, _real, iRRAM::REAL::geterror(), and iRRAM::max().
Referenced by geterror().
geterror() [2/2]
sizetype iRRAM::COMPLEX::geterror () const inline
Definition at line 68 of file COMPLEX.h.
References geterror().
Referenced by geterror().
seterror()
void iRRAM::COMPLEX::seterror (sizetype error)
Definition at line 41 of file COMPLEX.cc.
References _imag, _real, and iRRAM::REAL::seterror().
Referenced by seterror().
Friends And Related Function Documentation
abs
REAL abs (const COMPLEX & z) friend
Definition at line 98 of file COMPLEX.cc.
Referenced by iRRAM::abs(), iRRAM::acos(), iRRAM::arg(), iRRAM::asin(), iRRAM::csqrt(), and iRRAM::log().
arg
REAL arg (const COMPLEX & z) friend
Definition at line 165 of file COMPLEX.cc.
Referenced by iRRAM::log().
geterror()
sizetype geterror (const COMPLEX & r) related
Definition at line 73 of file COMPLEX.h.
References geterror().
imag
REAL imag (const COMPLEX & z) friend
Definition at line 95 of file COMPLEX.cc.
Referenced by iRRAM::abs(), iRRAM::acos(), iRRAM::arg(), iRRAM::asin(), iRRAM::atan(), iRRAM::cos(), iRRAM::cosh(), iRRAM::csqrt(), iRRAM::exp(), iRRAM::sin(), and iRRAM::sinh().
operator*
COMPLEX operator* (const COMPLEX & x, const COMPLEX & y) friend
Definition at line 74 of file COMPLEX.cc.
operator+
COMPLEX operator+ (const COMPLEX & x, const COMPLEX & y) friend
Definition at line 56 of file COMPLEX.cc.
operator- [1/2]
COMPLEX operator- (const COMPLEX & x, const COMPLEX & y) friend
Definition at line 62 of file COMPLEX.cc.
operator- [2/2]
COMPLEX operator- (const COMPLEX & x) friend
Definition at line 68 of file COMPLEX.cc.
operator/
COMPLEX operator/ (const COMPLEX & x, const COMPLEX & y) friend
Definition at line 82 of file COMPLEX.cc.
real
REAL real (const COMPLEX & z) friend
Definition at line 92 of file COMPLEX.cc.
Referenced by iRRAM::abs(), iRRAM::acos(), iRRAM::arg(), iRRAM::asin(), iRRAM::atan(), iRRAM::cos(), iRRAM::cosh(), iRRAM::csqrt(), iRRAM::exp(), iRRAM::sin(), and iRRAM::sinh().
seterror()
void seterror (COMPLEX & r, const sizetype & err) related
Definition at line 75 of file COMPLEX.h.
References iRRAM::acos(), iRRAM::acosec(), iRRAM::acosech(), iRRAM::acosh(), iRRAM::acotan(), iRRAM::acoth(), iRRAM::asec(), iRRAM::asech(), iRRAM::asin(), iRRAM::asinh(), iRRAM::atan(), iRRAM::atanh(), iRRAM::cos(), iRRAM::cosec(), iRRAM::cosech(), iRRAM::cosh(), iRRAM::cotan(), iRRAM::coth(), iRRAM::csqrt(), iRRAM::exp(), iRRAM::log(), iRRAM::sec(), iRRAM::sech(), seterror(), iRRAM::sin(), iRRAM::sinh(), iRRAM::sqrt(), iRRAM::tan(), and iRRAM::tanh().
Member Data Documentation
_imag
REAL iRRAM::COMPLEX::_imag
Definition at line 69 of file COMPLEX.h.
Referenced by iRRAM::abs(), adderror(), geterror(), iRRAM::imag(), iRRAM::operator*(), iRRAM::operator+(), iRRAM::operator-(), iRRAM::operator/(), and seterror().
_real
REAL iRRAM::COMPLEX::_real
Definition at line 69 of file COMPLEX.h.
Referenced by iRRAM::abs(), adderror(), geterror(), iRRAM::operator*(), iRRAM::operator+(), iRRAM::operator-(), iRRAM::operator/(), iRRAM::real(), and seterror().
The documentation for this class was generated from the following files:
include/iRRAM/COMPLEX.h
src/COMPLEX.cc