iRRAM: iRRAM::REAL Class Reference
iRRAM::REAL Class Reference final
Data Types
#include <REAL.h>
Public Member Functions
REAL ()
REAL (int i)
REAL (const std::string &s)
REAL (const char *s)
REAL (const DYADIC &y)
REAL (const REAL &y)
REAL (REAL &&y) noexcept
REAL (double d)
REAL (const INTEGER &y)
REAL (const RATIONAL &y)
REAL & operator= (const REAL &y)
REAL & operator= (REAL &&y) noexcept
~REAL ()
REAL & operator+= (const REAL &)
REAL operator- () const
REAL & operator-= (const REAL &y)
REAL & operator-= (int n)
REAL & operator*= (const REAL &y)
REAL & operator*= (int n)
REAL & operator/= (const REAL &y)
DYADIC as_DYADIC (const int p) const
DYADIC as_DYADIC () const
double as_double (const int p=53) const
INTEGER as_INTEGER () const
void rcheck (int n=50) const
void adderror (sizetype error)
void seterror (sizetype error)
void geterror (sizetype &error) const
sizetype geterror () const
void getsize (sizetype &error) const
sizetype getsize () const
void to_formal_ball (DYADIC &, sizetype &error) const
Public Attributes
double_pair dp
Closed double interval containg x.
MP_type value
Center of the current interval containing the real value x.
sizetype error
Radius of the current interval containing the real value x.
sizetype vsize
Tight sizetype typed approximation to value.
Friends
REAL operator+ (const REAL &, const REAL &)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator+ (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator+ (const B &b, const A &a)
REAL operator- (const REAL &x, const REAL &y)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator- (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator- (const B &b, const A &a)
REAL operator* (const REAL &x, const REAL &y)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator* (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator* (const B &b, const A &a)
REAL operator/ (const REAL &x, const REAL &y)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator/ (const A &a, const B &b)
template<typename A , typename B >
enable_if_compat< REAL, A, B > operator/ (const B &b, const A &a)
REAL operator<< (const REAL &x, int n)
REAL operator>> (const REAL &x, int n)
REAL sqrt (const REAL &x)
REAL square (const REAL &x)
REAL scale (const REAL &x, const int k)
LAZY_BOOLEAN operator< (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator<= (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator> (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator>= (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator== (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator!= (const REAL &x, const REAL &y)
LAZY_BOOLEAN positive (const REAL &x, const int k)
LAZY_BOOLEAN bound (const REAL &x, const int k)
DYADIC approx (const REAL &x, const int p)
Computes a dyadic approximation to x that is accurate to 2^p.
std::string swrite (const REAL &x, const int p, const float_form form)
int upperbound (const REAL &x)
int size (const REAL &x)
Returns a tight bound to the logarithmic value of |x|: \(2^{k-2}-2^e\leq|x|<2^k\), where e is x.vsize.exponent.
REAL abs (const REAL &x)
REAL limit_lip (REAL f(int, const REAL &), int lip, bool on_domain(const REAL &), const REAL &x)
REAL limit_lip (REAL f(int, const REAL &), int lip(const REAL &), const REAL &x)
REAL limit_lip (REAL f(int, const REAL &, const REAL &), int lip, bool on_domain(const REAL &, const REAL &), const REAL &x, const REAL &y)
REAL lipschitz (REAL f(const REAL &), int lip, bool on_domain(const REAL &), const REAL &x)
REAL lipschitz (REAL f(const REAL &), REAL lip_f(const REAL &), bool on_domain(const REAL &), const REAL &x)
REAL lipschitz (REAL f(const REAL &, const REAL &), int lip, bool on_domain(const REAL &, const REAL &), const REAL &x, const REAL &y)
REAL lipschitz (REAL f(int, const REAL &), int lip, bool on_domain(int k, const REAL &), int k, const REAL &x)
REAL lipschitz (REAL f(int, const REAL &, const REAL &), int lip, bool on_domain(int k, const REAL &, const REAL &), int k, const REAL &x, const REAL &y)
REAL lipschitz (REAL f(const REAL &), REAL lip_f(const REAL &), const REAL &x)
void swap (REAL &, REAL &) noexcept
REAL strtoREAL2 (const char *s, char **endptr)
Converts a base-10 string in scientific notation to REAL.
Related Functions
(Note that these are not member functions.)
sizetype geterror (const REAL &r)
void seterror (REAL &r, const sizetype &err)
int module (REAL(*f)(const REAL &), const REAL &x, int p)
Detailed Description
Definition at line 44 of file REAL.h.
Constructor & Destructor Documentation
iRRAM::REAL::REAL () inline
Definition at line 482 of file REAL.h.
Referenced by iRRAM::abs(), iRRAM::approx(), as_INTEGER(), getsize(), iRRAM::operator*(), iRRAM::operator+(), operator-(), iRRAM::operator-(), iRRAM::operator/(), REAL(), iRRAM::round(), iRRAM::round2(), iRRAM::rshow(), iRRAM::scale(), iRRAM::size(), iRRAM::square(), iRRAM::strtoREAL(), iRRAM::strtoREAL2(), and iRRAM::swrite().
iRRAM::REAL::REAL (int i) inline
Definition at line 484 of file REAL.h.
References iRRAM::state_t::highlevel, iRRAM_unlikely, and iRRAM::state.
iRRAM::REAL::REAL (const std::string & s) explicit
Definition at line 827 of file REALS.cc.
iRRAM::REAL::REAL (const char * s) explicit
Definition at line 828 of file REALS.cc.
iRRAM::REAL::REAL (const DYADIC & y)
Definition at line 820 of file REALS.cc.
References error, MP_duplicate_w_init, MP_getsize, iRRAM::sizetype_exact(), iRRAM::DYADIC::value, value, and vsize.
iRRAM::REAL::REAL (const REAL & y) inline
Definition at line 498 of file REAL.h.
References iRRAM_unlikely, and value.
iRRAM::REAL::REAL (REAL && y) inline noexcept
Definition at line 504 of file REAL.h.
References value.
iRRAM::REAL::REAL (double d) inline
Definition at line 490 of file REAL.h.
References iRRAM::state_t::highlevel, iRRAM_unlikely, and iRRAM::state.
iRRAM::REAL::REAL (const INTEGER & y)
Definition at line 882 of file REALS.cc.
References error, MP_getsize, MP_init, MP_INTEGER_to_mp, iRRAM::sizetype_exact(), value, and vsize.
iRRAM::REAL::REAL (const RATIONAL & y)
Definition at line 868 of file REALS.cc.
References error, MP_duplicate_w_init, MP_getsize, MP_rat_get_denominator, MP_rat_get_numerator, REAL(), value, and vsize.
iRRAM::REAL::~REAL () inline
Definition at line 474 of file REAL.h.
References iRRAM_unlikely, MP_clear, and value.
Member Function Documentation
void iRRAM::REAL::adderror (sizetype error)
Definition at line 766 of file REALS.cc.
References adderror(), iRRAM::sizetype_inc(), and value.
Referenced by iRRAM::COMPLEX::adderror(), iRRAM::SPARSEREALMATRIX::adderror(), adderror(), iRRAM::limit_lip(), iRRAM::lipschitz(), and iRRAM::module().
double iRRAM::REAL::as_double (const int p = 53) const
Definition at line 1109 of file REALS.cc.
References approx, bound, MP_mp_to_double, size, and iRRAM::DYADIC::value.
Referenced by operator/=().
DYADIC iRRAM::REAL::as_DYADIC (const int p) const
Definition at line 1104 of file REALS.cc.
References approx.
DYADIC iRRAM::REAL::as_DYADIC () const
Definition at line 1106 of file REALS.cc.
References approx, and iRRAM::DYADIC::getprec().
Referenced by operator/=().
INTEGER iRRAM::REAL::as_INTEGER () const
Definition at line 830 of file REALS.cc.
References iRRAM::state_t::ACTUAL_STACK, as_INTEGER(), iRRAM::iRRAM_thread_data_class::cache_mpi, error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, MP_int_duplicate_w_init, MP_int_init, MP_int_type, MP_mp_to_INTEGER, MP_sign, iRRAM::iRRAM_cache< DATA >::put(), REAL(), REITERATE, iRRAM::sizetype_less(), iRRAM::sizetype_set(), iRRAM::state, iRRAM::state_t::thread_data_address, and value.
Referenced by as_INTEGER(), operator/=(), iRRAM::round(), and iRRAM::round2().
void iRRAM::REAL::geterror (sizetype & error) const
Definition at line 788 of file REALS.cc.
References geterror(), and value.
Referenced by iRRAM::euler(), iRRAM::COMPLEX::geterror(), iRRAM::SPARSEREALMATRIX::geterror(), geterror(), iRRAM::iteration(), iRRAM::limit(), iRRAM::limit_hint(), iRRAM::limit_lip(), iRRAM::lipschitz(), iRRAM::ln2(), iRRAM::module(), iRRAM::pi(), iRRAM::scale(), and to_formal_ball().
sizetype iRRAM::REAL::geterror () const inline
Definition at line 310 of file REAL.h.
References geterror(), and getsize().
Referenced by geterror().
void iRRAM::REAL::getsize (sizetype & error) const
Definition at line 798 of file REALS.cc.
References getsize(), and value.
Referenced by getsize(), iRRAM::iteration(), iRRAM::lipschitz(), and iRRAM::sqrt().
sizetype iRRAM::REAL::getsize () const inline
Definition at line 312 of file REAL.h.
References getsize(), MP_type, REAL(), and to_formal_ball().
Referenced by geterror(), and getsize().
REAL& iRRAM::REAL::operator*= (const REAL & y) inline
Definition at line 138 of file REAL.h.
References operator/.
REAL & iRRAM::REAL::operator*= (int n) inline
Definition at line 705 of file REAL.h.
References dp, iRRAM_unlikely, and value.
REAL & iRRAM::REAL::operator+= (const REAL & y) inline
Definition at line 608 of file REAL.h.
References dp, iRRAM_unlikely, and value.
REAL iRRAM::REAL::operator- () const inline
Definition at line 649 of file REAL.h.
References dp, iRRAM_unlikely, REAL(), and value.
REAL & iRRAM::REAL::operator-= (const REAL & y) inline
Definition at line 657 of file REAL.h.
REAL & iRRAM::REAL::operator-= (int n) inline
Definition at line 658 of file REAL.h.
REAL& iRRAM::REAL::operator/= (const REAL & y) inline
Definition at line 154 of file REAL.h.
References abs, approx, as_double(), as_DYADIC(), as_INTEGER(), bound, limit_lip, lipschitz, operator!=, operator<, operator<<, operator<=, operator==, operator>, operator>=, operator>>, positive, rcheck(), scale, size, sqrt, square, strtoREAL2, swap, swrite, and upperbound.
REAL & iRRAM::REAL::operator= (const REAL & y) inline
Definition at line 517 of file REAL.h.
References iRRAM::state_t::ACTUAL_STACK, dp, iRRAM_unlikely, iRRAM::ITERATION_DATA::prec_step, iRRAM::state, and value.
REAL & iRRAM::REAL::operator= (REAL && y) inline noexcept
Definition at line 572 of file REAL.h.
References dp, error, iRRAM_unlikely, swap, iRRAM::swap(), value, and vsize.
void iRRAM::REAL::seterror (sizetype error)
Definition at line 777 of file REALS.cc.
References error, seterror(), and value.
Referenced by iRRAM::euler(), iRRAM::iteration(), iRRAM::limit(), iRRAM::limit_hint(), iRRAM::module(), iRRAM::COMPLEX::seterror(), iRRAM::SPARSEREALMATRIX::seterror(), and seterror().
void iRRAM::REAL::to_formal_ball (DYADIC & d, sizetype & error) const
Definition at line 808 of file REALS.cc.
References geterror(), MP_duplicate_wo_init, iRRAM::DYADIC::value, and value.
Referenced by getsize().
Friends And Related Function Documentation
REAL abs (const REAL & x) friend
Definition at line 817 of file REAL.h.
Referenced by iRRAM::maximum(), iRRAM::minimum(), operator/=(), and iRRAM::round().
DYADIC approx (const REAL & x, const int p) friend
Computes a dyadic approximation to x that is accurate to 2^p.
This is a multi-valued function.
Reiteration is used to ensure \(x_\varepsilon\leq2^{p+1}\). The computed value at least as precise as \(x_c\) rounded to a multiple of \(2^{p-1}\).
Parameters
x the real number to approximate
p accuracy
Returns
a dyadic approximation q that satisfies |x-q|<2^p.
Exceptions
Iteration when \(2^{p+1}<x_\varepsilon\)
See also
REITERATE
Definition at line 605 of file REALS.cc.
Referenced by iRRAM::approx(), as_double(), as_DYADIC(), iRRAM::module(), and operator/=().
LAZY_BOOLEAN bound (const REAL & x, const int k) friend
Definition at line 726 of file REALS.cc.
Referenced by as_double(), iRRAM::bound(), and operator/=().
sizetype geterror (const REAL & r) related
Definition at line 354 of file REAL.h.
References geterror().
REAL limit_lip (REAL fint, const REAL &, int lip, bool on_domainconst REAL &, const REAL & x) friend
Referenced by operator/=().
REAL limit_lip (REAL fint, const REAL &, int lipconst REAL &, const REAL & x) friend
REAL limit_lip (REAL fint, const REAL &, const REAL &, int lip, bool on_domainconst REAL &, const REAL &, const REAL & x, const REAL & y) friend
REAL lipschitz (REAL fconst REAL &, int lip, bool on_domainconst REAL &, const REAL & x) friend
Referenced by operator/=().
REAL lipschitz (REAL fconst REAL &, REAL lip_fconst REAL &, bool on_domainconst REAL &, const REAL & x) friend
REAL lipschitz (REAL fconst REAL &, const REAL &, int lip, bool on_domainconst REAL &, const REAL &, const REAL & x, const REAL & y) friend
REAL lipschitz (REAL fint, const REAL &, int lip, bool on_domainint k, const REAL &, int k, const REAL & x) friend
REAL lipschitz (REAL fint, const REAL &, const REAL &, int lip, bool on_domainint k, const REAL &, const REAL &, int k, const REAL & x, const REAL & y) friend
REAL lipschitz (REAL fconst REAL &, REAL lip_fconst REAL &, const REAL & x) friend
int module (REAL(*)(const REAL &) f, const REAL & x, int p) related
Definition at line 1121 of file REALS.cc.
Referenced by seterror().
LAZY_BOOLEAN operator!= (const REAL & x, const REAL & y) friend
Definition at line 815 of file REAL.h.
Referenced by operator/=().
REAL operator* (const REAL & x, const REAL & y) friend
Definition at line 663 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator* (const A & a, const B & b) friend
Definition at line 127 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator* (const B & b, const A & a) friend
Definition at line 133 of file REAL.h.
REAL operator+ (const REAL & x, const REAL & y) friend
Definition at line 587 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator+ (const A & a, const B & b) friend
Definition at line 93 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator+ (const B & b, const A & a) friend
Definition at line 99 of file REAL.h.
REAL operator- (const REAL & x, const REAL & y) friend
Definition at line 623 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator- (const A & a, const B & b) friend
Definition at line 108 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator- (const B & b, const A & a) friend
Definition at line 114 of file REAL.h.
REAL operator/ (const REAL & x, const REAL & y) friend
Definition at line 720 of file REAL.h.
Referenced by operator*=().
template<typename A , typename B > enable_if_compat<REAL,A,B> operator/ (const A & a, const B & b) friend
Definition at line 144 of file REAL.h.
template<typename A , typename B > enable_if_compat<REAL,A,B> operator/ (const B & b, const A & a) friend
Definition at line 150 of file REAL.h.
LAZY_BOOLEAN operator< (const REAL & x, const REAL & y) friend
Definition at line 800 of file REAL.h.
Referenced by operator/=().
REAL operator<< (const REAL & x, int n) friend
Definition at line 584 of file REAL.h.
Referenced by operator/=().
LAZY_BOOLEAN operator<= (const REAL & x, const REAL & y) friend
Definition at line 811 of file REAL.h.
Referenced by operator/=().
LAZY_BOOLEAN operator== (const REAL & x, const REAL & y) friend
Definition at line 814 of file REAL.h.
Referenced by operator/=().
LAZY_BOOLEAN operator> (const REAL & x, const REAL & y) friend
Definition at line 812 of file REAL.h.
Referenced by operator/=().
LAZY_BOOLEAN operator>= (const REAL & x, const REAL & y) friend
Definition at line 813 of file REAL.h.
Referenced by operator/=().
REAL operator>> (const REAL & x, int n) friend
Definition at line 585 of file REAL.h.
Referenced by operator/=().
LAZY_BOOLEAN positive (const REAL & x, const int k) friend
Definition at line 571 of file REALS.cc.
Referenced by operator/=(), and iRRAM::positive().
REAL scale (const REAL & x, const int k) friend
Definition at line 553 of file REALS.cc.
Referenced by operator/=(), iRRAM::operator<<(), iRRAM::operator>>(), and iRRAM::scale().
void seterror (REAL & r, const sizetype & err) related
Definition at line 356 of file REAL.h.
References iRRAM::atoREAL(), module(), seterror(), iRRAM::strtoREAL(), and strtoREAL2.
int size (const REAL & x) friend
Returns a tight bound to the logarithmic value of |x|: \(2^{k-2}-2^e\leq|x|<2^k\), where e is x.vsize.exponent.
This is a multi-valued function.
For \(\hat x=m\cdot2^e\) = x.vsize and \(x_\varepsilon\) = x.error, this function computes \(k=\lceil\log_2(\hat x+x_\varepsilon)\rceil>\log_2|x|\) and via reiteration enforces that \(\hat x\geq x_\varepsilon+2^{k-2}\) which is equivalent to \(2^{k-2}\leq\hat x-x_\varepsilon=(m-1)\cdot2^e-x_\varepsilon+2^e \leq|x|+2^e\), the guarrantee therefore is \(2^{k-2}-2^e\leq|x|<2^k\).
Parameters
x non-zero real number
Returns
\(k\in\mathbb Z:2^{k-2}-2^e\leq|x|<2^k\), where e is x.vsize.exponent and min_exponent <= k < MP_max
Exceptions
iRRAM_Numerical_Exception(iRRAM_underflow_error) if x is exact with value zero. If x is not exact but zero, reiterations will be performed.
See also
REITERATE
Todo:
According to documentation, size(const REAL &) should compute \(\begin{cases} 1+\lfloor\log_2|x|\rfloor\text,&x\neq 0 \\ 1+\lceil\log_2|x|\rceil\text,&x\neq 0 \\ \text{undef,}&x=0 \end{cases}\) but it does compute \(\begin{cases} i+\lfloor\log_2|x|\rfloor\text,&x\neq 0, i\in\{1,2,3\} \\ \text{undef,}&x=0 \end{cases}\)
Definition at line 666 of file REALS.cc.
Referenced by as_double(), operator/=(), iRRAM::size(), and iRRAM::swrite().
REAL sqrt (const REAL & x) friend
Definition at line 75 of file sqrt.cc.
Referenced by iRRAM::abs(), operator/=(), and iRRAM::round().
REAL square (const REAL & x) friend
Definition at line 778 of file REAL.h.
Referenced by iRRAM::abs(), operator/=(), and iRRAM::power().
REAL strtoREAL2 (const char * s, char ** endptr) friend
Converts a base-10 string in scientific notation to REAL.
If \(p\) is the current working precision of iRRAM, \(k\) the number of digits in the integer part, \(z\) the number of leading zero-digits (including the fractional part) and \(g\) the exponent, and the represented value is not zero, then the result has a relative precision of roughly \((g+k-z)\log_2(10)-p\) bits, which corresponds to an absolute accuracy of \(2^p\).
Parameters
[in] s pointer to base-10 string; format: WSDFE where
W = optional whitespace; it is discarded
S = optional sign
D = optional string of digits 0..9
F = optional: . followed by optional string of digits 0..9
E = optional: e or E followed by an optional sign followed by a string of digits 0..9
DF must be non-empty and not just contain .
[out] endptr when non-NULL, the pointer to the end of the represented number is stored in *endptr
Returns
a REAL object accurate to the current working precision.
Proof
The precision depends only on DF and E; let \(x_k\ldots x_{-n}=DF[1..|F|]\) and \(z\in\mathbb N:x[1..z]=\texttt 0^z\). To represent zero up to any accuracy, only 1 bit is required. So let \(x\neq0\) and \(b\cdot2^c\) with \(b\in[2^{-1};1)\) be the result. Then the error is
\[ (*)=|10^g\sum_{i=-n}^{k-z} x_i\cdot 10^i-2^cb| =|2^{\overbrace{(g+k-z+1)\log_2(10)}^{=:q}} \underbrace{\sum_{i=-n-(k-z+1)}^{-1}x_{i+k-z+1}\cdot10^i}_{=:x'\in[10^{-1};1)} -2^cb| \]
Now, MPFR's mpfr_strtofr() guarantees for the exact input \(2^qx'=:2^{\overline q}\overline b\) with \(\overline b\in[2^{-1};1)\) that the error is \(|2^{\overline q}\overline b-2^cb|<2^{\overline q-m}\), therefore
\[(*)=|2^qx'-2^{\overline q}\overline b+2^{\overline q}\overline b-2^cb| <|2^qx'-2^{\overline q}\overline b|+2^{\overline q-m}=2^{\overline q-m} \]
Since \(2^{\overline q}/2\leq 2^{\overline q}\overline b=2^qx'<2^q\), the error is bounded, \((*)<2^p\), when \(\overline q-p<m\leq q+1-p<\lceil(g+k-z+1)\log_2(10)\rceil+1-p\leq m'\). The exact precision is \(\max(10,m')\) where \(m'=1+\begin{cases} 1&z=k+n+1\\ \lfloor((g+k-z+1)\cdot 10+2)/3+1\rfloor-p&\text{otherwise} \end{cases}\)
Definition at line 937 of file REALS.cc.
Referenced by operator/=(), and seterror().
void swap (REAL & a, REAL & b) friend
Definition at line 539 of file REAL.h.
Referenced by operator/=(), operator=(), and iRRAM::swap().
std::string swrite (const REAL & x, const int p, const float_form form) friend
Definition at line 199 of file REALS.cc.
Referenced by operator/=(), iRRAM::round(), iRRAM::rshow(), iRRAM::rwrite(), iRRAM::rwritee(), and iRRAM::swrite().
int upperbound (const REAL & x) friend
Definition at line 696 of file REALS.cc.
Referenced by operator/=(), and iRRAM::upperbound().
Member Data Documentation
double_pair iRRAM::REAL::dp
Closed double interval containg x.
Let this REAL object denote \(x\in\mathbb R\), then in this documentation dp.lower_pos is denoted as \(x_L\), dp.upper_neg is denoted as \(x_{-U}\) and likewise -dp.upper_neg is \(x_U\). This way of approximating reals is only used in the Iteration with actual_step == 1.
Invariant
value == NULL \(\Longrightarrow x_L\leq x\leq x_U\).
Definition at line 268 of file REAL.h.
Referenced by iRRAM::abs(), iRRAM::operator*(), operator*=(), iRRAM::operator+(), operator+=(), operator-(), iRRAM::operator-(), iRRAM::operator/(), iRRAM::operator<(), operator=(), rcheck(), iRRAM::round(), and iRRAM::square().
sizetype iRRAM::REAL::error
Radius of the current interval containing the real value x.
Let this REAL object denote \(x\in\mathbb R\), then in this documentation error is referred to as \(x_\varepsilon\). It may very well differ from one Iteration to the next.
Invariant
value != NULL \(\Longrightarrow|x-x_c|\leq x_\varepsilon\)
Definition at line 291 of file REAL.h.
Referenced by iRRAM::approx(), as_INTEGER(), iRRAM::bound(), iRRAM::limit_lip(), iRRAM::lipschitz(), operator=(), iRRAM::positive(), rcheck(), REAL(), iRRAM::round(), iRRAM::rshow(), seterror(), iRRAM::size(), iRRAM::sqrt(), iRRAM::swrite(), and iRRAM::upperbound().
MP_type iRRAM::REAL::value
Center of the current interval containing the real value x.
Let this REAL object denote \(x\in\mathbb R\), then in this documentation value is referred to as \(x_c\). It may differ from one Iteration to the next.
Invariant
value != NULL \(\Longrightarrow|x-x_c|\leq x_\varepsilon\)
Definition at line 280 of file REAL.h.
Referenced by iRRAM::abs(), adderror(), iRRAM::approx(), as_INTEGER(), iRRAM::bound(), geterror(), getsize(), iRRAM::limit_lip(), iRRAM::lipschitz(), iRRAM::operator*(), operator*=(), iRRAM::operator+(), operator+=(), operator-(), iRRAM::operator-(), iRRAM::operator/(), iRRAM::operator<(), operator=(), iRRAM::positive(), rcheck(), REAL(), iRRAM::round(), iRRAM::rshow(), iRRAM::scale(), seterror(), iRRAM::size(), iRRAM::sqrt(), iRRAM::square(), iRRAM::strtoREAL2(), iRRAM::swrite(), to_formal_ball(), iRRAM::upperbound(), and ~REAL().
sizetype iRRAM::REAL::vsize
Tight sizetype typed approximation to value.
Let this REAL object denote \(x\in\mathbb R\), then in this documentation vsize is referred to as \(\hat x\). It may differ from one Iteration to the next.
Invariant
value != NULL \(\Longrightarrow\texttt{vsize}=m\cdot2^e:(m-1)\cdot2^e \leq|x_c|<m\cdot2^e\)
Definition at line 304 of file REAL.h.
Referenced by iRRAM::bound(), operator=(), iRRAM::positive(), rcheck(), REAL(), iRRAM::round(), iRRAM::rshow(), iRRAM::size(), iRRAM::swrite(), and iRRAM::upperbound().
The documentation for this class was generated from the following files:
include/iRRAM/REAL.h
src/REALS.cc