iRRAM: iRRAM::iRRAM_cache< DATA > Class Template Reference
iRRAM::iRRAM_cache< DATA > Class Template Reference
#include <cache.h>
Public Member Functions
void put (const DATA &x)
bool get (DATA &x) noexcept(noexcept(x=x))
void modify (const DATA &x) noexcept(noexcept(const_cast< DATA &>(x)=x))
void rewind () noexcept
void clear ()
void activate ()
Public Attributes
std::vector< typename get_type< DATA >::type > data
unsigned int current = 0
bool active = false
Detailed Description
template<class DATA>
class iRRAM::iRRAM_cache< DATA >
Definition at line 75 of file cache.h.
Member Function Documentation
activate()
template<class DATA> void iRRAM::iRRAM_cache< DATA >::activate () inline
Definition at line 108 of file cache.h.
clear()
template<class DATA> void iRRAM::iRRAM_cache< DATA >::clear () inline virtual
Implements iRRAM::iRRAM_cache_type.
Definition at line 102 of file cache.h.
get()
template<class DATA> bool iRRAM::iRRAM_cache< DATA >::get (DATA & x) inline noexcept
Definition at line 88 of file cache.h.
Referenced by iRRAM::approx(), iRRAM::REAL::as_INTEGER(), iRRAM::check(), iRRAM::choose(), iRRAM::irstream::irstream(), iRRAM::limit_mv(), iRRAM::module(), iRRAM::LAZY_BOOLEAN::operator bool(), iRRAM::orstream::orstream(), iRRAM::size(), iRRAM::swrite(), and iRRAM::upperbound().
modify()
template<class DATA> void iRRAM::iRRAM_cache< DATA >::modify (const DATA & x) inline noexcept
Definition at line 94 of file cache.h.
Referenced by iRRAM::limit_mv().
put()
template<class DATA> void iRRAM::iRRAM_cache< DATA >::put (const DATA & x) inline
Definition at line 82 of file cache.h.
Referenced by iRRAM::approx(), iRRAM::REAL::as_INTEGER(), iRRAM::check(), iRRAM::choose(), iRRAM::irstream::irstream(), iRRAM::limit_mv(), iRRAM::module(), iRRAM::LAZY_BOOLEAN::operator bool(), iRRAM::orstream::orstream(), iRRAM::size(), iRRAM::swrite(), and iRRAM::upperbound().
rewind()
template<class DATA> void iRRAM::iRRAM_cache< DATA >::rewind () inline virtual noexcept
Implements iRRAM::iRRAM_cache_type.
Definition at line 98 of file cache.h.
Member Data Documentation
active
template<class DATA> bool iRRAM::iRRAM_cache< DATA >::active = false
Definition at line 80 of file cache.h.
current
template<class DATA> unsigned int iRRAM::iRRAM_cache< DATA >::current = 0
Definition at line 79 of file cache.h.
data
template<class DATA> std::vector<typename get_type<DATA>::type> iRRAM::iRRAM_cache< DATA >::data
Definition at line 78 of file cache.h.
The documentation for this class was generated from the following file:
include/iRRAM/cache.h