iRRAM: Trigonometry
Trigonometry
Mathematical functions
Functions
COMPLEX iRRAM::sin (const COMPLEX &z)
COMPLEX iRRAM::cos (const COMPLEX &z)
COMPLEX iRRAM::tan (const COMPLEX &z)
COMPLEX iRRAM::cotan (const COMPLEX &z)
COMPLEX iRRAM::sec (const COMPLEX &z)
COMPLEX iRRAM::cosec (const COMPLEX &z)
COMPLEX iRRAM::sinh (const COMPLEX &z)
COMPLEX iRRAM::cosh (const COMPLEX &z)
COMPLEX iRRAM::tanh (const COMPLEX &z)
COMPLEX iRRAM::coth (const COMPLEX &z)
COMPLEX iRRAM::sech (const COMPLEX &z)
COMPLEX iRRAM::cosech (const COMPLEX &z)
COMPLEX iRRAM::asin (const COMPLEX &z)
COMPLEX iRRAM::acos (const COMPLEX &z)
COMPLEX iRRAM::atan (const COMPLEX &z)
COMPLEX iRRAM::acotan (const COMPLEX &z)
COMPLEX iRRAM::asec (const COMPLEX &z)
COMPLEX iRRAM::acosec (const COMPLEX &z)
COMPLEX iRRAM::asinh (const COMPLEX &z)
COMPLEX iRRAM::acosh (const COMPLEX &z)
COMPLEX iRRAM::atanh (const COMPLEX &z)
COMPLEX iRRAM::acoth (const COMPLEX &z)
COMPLEX iRRAM::asech (const COMPLEX &z)
COMPLEX iRRAM::acosech (const COMPLEX &z)
REAL iRRAM::sin (const REAL &x)
REAL iRRAM::cos (const REAL &x)
REAL iRRAM::tan (const REAL &x)
REAL iRRAM::cotan (const REAL &x)
REAL iRRAM::sec (const REAL &x)
REAL iRRAM::cosec (const REAL &x)
REAL iRRAM::atan (const REAL &x)
REAL iRRAM::asin (const REAL &x)
REAL iRRAM::acos (const REAL &x)
REAL iRRAM::acotan (const REAL &x)
REAL iRRAM::asec (const REAL &x)
REAL iRRAM::acosec (const REAL &x)
REAL iRRAM::sinh (const REAL &x)
REAL iRRAM::cosh (const REAL &x)
REAL iRRAM::tanh (const REAL &x)
REAL iRRAM::coth (const REAL &x)
REAL iRRAM::sech (const REAL &x)
REAL iRRAM::cosech (const REAL &x)
REAL iRRAM::asinh (const REAL &x)
REAL iRRAM::acosh (const REAL &x)
REAL iRRAM::atanh (const REAL &x)
REAL iRRAM::acoth (const REAL &x)
REAL iRRAM::asech (const REAL &x)
REAL iRRAM::acosech (const REAL &x)
Detailed Description
Function Documentation
REAL iRRAM::acos (const REAL & x)
Definition at line 280 of file sin_cos.cc.
References iRRAM::asin(), and iRRAM::pi().
COMPLEX iRRAM::acos (const COMPLEX & z)
Definition at line 431 of file COMPLEX.cc.
References iRRAM::COMPLEX::abs, iRRAM::COMPLEX::COMPLEX(), iRRAM::COMPLEX::imag, iRRAM::log(), iRRAM::COMPLEX::real, and iRRAM::sqrt().
Referenced by iRRAM::arg(), iRRAM::asec(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::acosec (const REAL & x)
Definition at line 282 of file sin_cos.cc.
References iRRAM::asin().
COMPLEX iRRAM::acosec (const COMPLEX & z)
Definition at line 497 of file COMPLEX.cc.
References iRRAM::asin(), and iRRAM::COMPLEX::COMPLEX().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::acosech (const REAL & x)
Definition at line 411 of file sin_cos.cc.
References iRRAM::asinh().
COMPLEX iRRAM::acosech (const COMPLEX & z)
Definition at line 569 of file COMPLEX.cc.
References iRRAM::asinh(), and iRRAM::COMPLEX::COMPLEX().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::acosh (const REAL & x)
Definition at line 407 of file sin_cos.cc.
References iRRAM::log(), and iRRAM::sqrt().
COMPLEX iRRAM::acosh (const COMPLEX & z)
Definition at line 521 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::log(), and iRRAM::sqrt().
Referenced by iRRAM::asech(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::acotan (const REAL & x)
COMPLEX iRRAM::acotan (const COMPLEX & z)
Definition at line 473 of file COMPLEX.cc.
References iRRAM::atan(), and iRRAM::COMPLEX::COMPLEX().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::acoth (const REAL & x)
Definition at line 409 of file sin_cos.cc.
References iRRAM::log().
COMPLEX iRRAM::acoth (const COMPLEX & z)
Definition at line 545 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::log().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::asec (const REAL & x)
Definition at line 281 of file sin_cos.cc.
References iRRAM::acos().
COMPLEX iRRAM::asec (const COMPLEX & z)
Definition at line 485 of file COMPLEX.cc.
References iRRAM::acos(), and iRRAM::COMPLEX::COMPLEX().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::asech (const REAL & x)
Definition at line 410 of file sin_cos.cc.
References iRRAM::acosh().
COMPLEX iRRAM::asech (const COMPLEX & z)
Definition at line 557 of file COMPLEX.cc.
References iRRAM::acosh(), and iRRAM::COMPLEX::COMPLEX().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::asin (const REAL & x)
Definition at line 279 of file sin_cos.cc.
References iRRAM::atan(), and iRRAM::sqrt().
COMPLEX iRRAM::asin (const COMPLEX & z)
Definition at line 407 of file COMPLEX.cc.
References iRRAM::COMPLEX::abs, iRRAM::COMPLEX::COMPLEX(), iRRAM::COMPLEX::imag, iRRAM::log(), iRRAM::COMPLEX::real, and iRRAM::sqrt().
Referenced by iRRAM::acos(), iRRAM::acosec(), iRRAM::arg(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::asinh (const REAL & x)
Definition at line 406 of file sin_cos.cc.
References iRRAM::log(), and iRRAM::sqrt().
COMPLEX iRRAM::asinh (const COMPLEX & z)
Definition at line 509 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::log(), and iRRAM::sqrt().
Referenced by iRRAM::acosech(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::atan (const REAL & x)
Definition at line 260 of file sin_cos.cc.
References iRRAM::abs(), iRRAM::atan(), iRRAM::choose(), iRRAM::limit_lip(), and iRRAM::pi().
COMPLEX iRRAM::atan (const COMPLEX & z)
Definition at line 454 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::COMPLEX::imag, iRRAM::log(), and iRRAM::COMPLEX::real.
Referenced by iRRAM::acotan(), iRRAM::asin(), iRRAM::atan(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::atanh (const REAL & x)
Definition at line 408 of file sin_cos.cc.
References iRRAM::log().
COMPLEX iRRAM::atanh (const COMPLEX & z)
Definition at line 533 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::log().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::cos (const REAL & x)
Definition at line 203 of file sin_cos.cc.
References iRRAM::limit_lip(), and iRRAM::pi().
COMPLEX iRRAM::cos (const COMPLEX & z)
Definition at line 236 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::exp(), iRRAM::COMPLEX::imag, iRRAM::COMPLEX::real, and iRRAM::sin().
Referenced by iRRAM::cosh(), iRRAM::cotan(), iRRAM::exp(), mpfr_ext_sin(), iRRAM::round(), iRRAM::sec(), iRRAM::COMPLEX::seterror(), iRRAM::sin(), iRRAM::sinh(), and iRRAM::tan().
COMPLEX iRRAM::cosec (const COMPLEX & z)
Definition at line 283 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::sin().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::cosec (const REAL & x)
Definition at line 287 of file sin_cos.cc.
References iRRAM::sin().
REAL iRRAM::cosech (const REAL & x)
Definition at line 310 of file sin_cos.cc.
References iRRAM::choose(), and iRRAM::exp().
COMPLEX iRRAM::cosech (const COMPLEX & z)
Definition at line 395 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::exp().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
COMPLEX iRRAM::cosh (const COMPLEX & z)
Definition at line 332 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::cos(), iRRAM::exp(), iRRAM::COMPLEX::imag, iRRAM::COMPLEX::real, and iRRAM::sin().
Referenced by iRRAM::round(), iRRAM::COMPLEX::seterror(), and iRRAM::tanh().
REAL iRRAM::cosh (const REAL & x)
Definition at line 346 of file sin_cos.cc.
References iRRAM::choose(), and iRRAM::exp().
COMPLEX iRRAM::cotan (const COMPLEX & z)
Definition at line 272 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::tan().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::cotan (const REAL & x)
Definition at line 288 of file sin_cos.cc.
References iRRAM::cos(), and iRRAM::sin().
COMPLEX iRRAM::coth (const COMPLEX & z)
Definition at line 371 of file COMPLEX.cc.
References iRRAM::exp().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::coth (const REAL & x)
Definition at line 385 of file sin_cos.cc.
References iRRAM::choose(), and iRRAM::exp().
REAL iRRAM::sec (const REAL & x)
Definition at line 286 of file sin_cos.cc.
References iRRAM::cos().
COMPLEX iRRAM::sec (const COMPLEX & z)
Definition at line 294 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::cos().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::sech (const REAL & x)
Definition at line 292 of file sin_cos.cc.
References iRRAM::choose(), and iRRAM::exp().
COMPLEX iRRAM::sech (const COMPLEX & z)
Definition at line 383 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), and iRRAM::exp().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::sin (const REAL & x)
Definition at line 208 of file sin_cos.cc.
References iRRAM::limit_lip().
COMPLEX iRRAM::sin (const COMPLEX & z)
Definition at line 212 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::cos(), iRRAM::exp(), iRRAM::COMPLEX::imag, and iRRAM::COMPLEX::real.
Referenced by iRRAM::cos(), iRRAM::cosec(), iRRAM::cosh(), iRRAM::cotan(), iRRAM::exp(), mpfr_ext_log(), mpfr_wrapper(), iRRAM::round(), iRRAM::COMPLEX::seterror(), iRRAM::sinh(), and iRRAM::tan().
COMPLEX iRRAM::sinh (const COMPLEX & z)
Definition at line 305 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::cos(), iRRAM::exp(), iRRAM::COMPLEX::imag, iRRAM::COMPLEX::real, and iRRAM::sin().
Referenced by iRRAM::round(), iRRAM::COMPLEX::seterror(), and iRRAM::tanh().
REAL iRRAM::sinh (const REAL & x)
Definition at line 328 of file sin_cos.cc.
References iRRAM::choose(), and iRRAM::exp().
REAL iRRAM::tan (const REAL & x)
Definition at line 213 of file sin_cos.cc.
References iRRAM::bound(), iRRAM::limit_lip(), iRRAM::modulo(), iRRAM::pi(), iRRAM::scale(), iRRAM::sin(), iRRAM::size(), and iRRAM::sqrt().
COMPLEX iRRAM::tan (const COMPLEX & z)
Definition at line 261 of file COMPLEX.cc.
References iRRAM::cos(), and iRRAM::sin().
Referenced by iRRAM::cotan(), mpfr_ext_cos(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
COMPLEX iRRAM::tanh (const COMPLEX & z)
Definition at line 359 of file COMPLEX.cc.
References iRRAM::cosh(), and iRRAM::sinh().
Referenced by iRRAM::round(), and iRRAM::COMPLEX::seterror().
REAL iRRAM::tanh (const REAL & x)
Definition at line 364 of file sin_cos.cc.
References iRRAM::choose(), and iRRAM::exp().