iRRAM: Mathematical functions
Mathematical functions
Modules
Limit operations
Trigonometry
Functions
DYADIC iRRAM::abs (const DYADIC &x)
int iRRAM::sign (const RATIONAL &x)
RATIONAL iRRAM::abs (RATIONAL x)
COMPLEX iRRAM::sqrt (const COMPLEX &z)
COMPLEX iRRAM::csqrt (const COMPLEX &z)
COMPLEX iRRAM::log (const COMPLEX &z)
COMPLEX iRRAM::exp (const COMPLEX &z)
INTEGER iRRAM::sqrt (const INTEGER &x)
INTEGER iRRAM::abs (const INTEGER &x)
REAL iRRAM::power (const REAL &x, const REAL &y)
REAL iRRAM::power (const REAL &x, int n)
REAL iRRAM::modulo (const REAL &x, const REAL &y)
REAL iRRAM::maximum (const REAL &x, const REAL &y)
REAL iRRAM::minimum (const REAL &x, const REAL &y)
REAL iRRAM::sqrt (const REAL &x)
Computes the square root of the argument x.
REAL iRRAM::root (const REAL &x, int n)
REAL iRRAM::exp (const REAL &x)
REAL iRRAM::log (const REAL &x)
REAL iRRAM::pi ()
REAL iRRAM::euler ()
REAL iRRAM::ln2 ()
REAL iRRAM::abs (const std::vector< REAL > &x)
REALMATRIX iRRAM::exp (const REALMATRIX &x)
Detailed Description
Function Documentation
abs() [1/4]
DYADIC iRRAM::abs (const DYADIC & x)
Definition at line 138 of file DYADIC.cc.
References MP_abs, MP_init, MP_type, and iRRAM::DYADIC::value.
abs() [2/4]
RATIONAL iRRAM::abs (RATIONAL x)
Definition at line 240 of file RATIONAL.cc.
References MP_rat_abs.
abs() [3/4]
INTEGER iRRAM::abs (const INTEGER & x) inline
Definition at line 449 of file INTEGER.h.
References MP_int_abs, MP_int_init, and MP_int_type.
abs() [4/4]
REAL iRRAM::abs (const std::vector< REAL > & x)
Definition at line 1167 of file REALS.cc.
References iRRAM::REAL::sqrt, and iRRAM::REAL::square.
csqrt()
COMPLEX iRRAM::csqrt (const COMPLEX & z)
Definition at line 138 of file COMPLEX.cc.
References iRRAM::COMPLEX::abs, iRRAM::bound(), iRRAM::COMPLEX::COMPLEX(), iRRAM::COMPLEX::imag, iRRAM::COMPLEX::real, iRRAM::size(), and iRRAM::sqrt().
Referenced by iRRAM::COMPLEX::seterror().
euler()
REAL iRRAM::euler ()
Definition at line 106 of file exp_log.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::bound(), iRRAM::REAL::geterror(), iRRAM::limit(), iRRAM::ln2(), iRRAM::pi(), iRRAM::scale(), iRRAM::REAL::seterror(), iRRAM::sqrt(), and iRRAM::state.
Referenced by iRRAM::round().
exp() [1/3]
REAL iRRAM::exp (const REAL & x)
Definition at line 81 of file exp_log.cc.
References iRRAM::bound(), iRRAM::limit_lip(), and iRRAM::positive().
exp() [2/3]
COMPLEX iRRAM::exp (const COMPLEX & z)
Definition at line 196 of file COMPLEX.cc.
References iRRAM::COMPLEX::COMPLEX(), iRRAM::cos(), iRRAM::COMPLEX::imag, iRRAM::COMPLEX::real, and iRRAM::sin().
Referenced by iRRAM::cos(), iRRAM::cosech(), iRRAM::cosh(), iRRAM::coth(), iRRAM::exp(), iRRAM::power(), iRRAM::round(), iRRAM::sech(), iRRAM::COMPLEX::seterror(), iRRAM::REALMATRIX::seterror(), iRRAM::sin(), iRRAM::sinh(), iRRAM::strtoREAL(), and iRRAM::tanh().
exp() [3/3]
REALMATRIX iRRAM::exp (const REALMATRIX & x)
Definition at line 321 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::bound, iRRAM::exp(), and iRRAM::REALMATRIX::limit_lip.
ln2()
REAL iRRAM::ln2 ()
Definition at line 39 of file pi_ln2.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::bound(), iRRAM::REAL::geterror(), iRRAM::limit(), iRRAM::state_t::ln2_err, iRRAM::state_t::ln2_val, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::pi(), iRRAM::power(), iRRAM::resources(), iRRAM::sqrt(), and iRRAM::state.
Referenced by iRRAM::euler(), iRRAM::log(), and iRRAM::round().
log() [1/2]
REAL iRRAM::log (const REAL & x)
Definition at line 179 of file exp_log.cc.
References iRRAM::limit_lip(), iRRAM::ln2(), iRRAM::scale(), iRRAM::size(), and iRRAM::sqrt().
log() [2/2]
COMPLEX iRRAM::log (const COMPLEX & z)
Definition at line 184 of file COMPLEX.cc.
References iRRAM::COMPLEX::abs, iRRAM::COMPLEX::arg, and iRRAM::COMPLEX::COMPLEX().
Referenced by iRRAM::acos(), iRRAM::acosh(), iRRAM::acoth(), iRRAM::asin(), iRRAM::asinh(), iRRAM::atan(), iRRAM::atanh(), iRRAM::power(), iRRAM::round(), and iRRAM::COMPLEX::seterror().
maximum()
REAL iRRAM::maximum (const REAL & x, const REAL & y)
Definition at line 1140 of file REALS.cc.
References iRRAM::REAL::abs.
Referenced by iRRAM::acos(), iRRAM::asin(), iRRAM::colsumnorm(), iRRAM::cos(), iRRAM::fabs(), iRRAM::intersect(), iRRAM::interval_hull(), iRRAM::mag(), iRRAM::maxnorm(), iRRAM::mig(), iRRAM::operator*(), iRRAM::operator-(), iRRAM::power(), iRRAM::round(), iRRAM::rowsumnorm(), iRRAM::sin(), and iRRAM::square().
minimum()
REAL iRRAM::minimum (const REAL & x, const REAL & y)
Definition at line 1152 of file REALS.cc.
References iRRAM::REAL::abs.
Referenced by iRRAM::acos(), iRRAM::asin(), iRRAM::cos(), iRRAM::fabs(), iRRAM::intersect(), iRRAM::interval_hull(), iRRAM::mig(), iRRAM::operator*(), iRRAM::operator-(), iRRAM::power(), iRRAM::round(), iRRAM::sin(), and iRRAM::square().
modulo()
REAL iRRAM::modulo (const REAL & x, const REAL & y)
Definition at line 1099 of file REALS.cc.
References iRRAM::round2().
Referenced by iRRAM::cos(), iRRAM::round(), iRRAM::sin(), and iRRAM::tan().
pi()
REAL iRRAM::pi ()
Definition at line 141 of file pi_ln2.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::geterror(), iRRAM::limit(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::state_t::pi_err, iRRAM::state_t::pi_val, iRRAM::resources(), and iRRAM::state.
Referenced by iRRAM::acos(), iRRAM::arg(), iRRAM::atan(), iRRAM::cos(), iRRAM::euler(), iRRAM::ln2(), iRRAM::round(), iRRAM::sin(), and iRRAM::tan().
power() [1/2]
REAL iRRAM::power (const REAL & x, const REAL & y)
Definition at line 1103 of file REALS.cc.
References iRRAM::exp(), and iRRAM::log().
power() [2/2]
REAL iRRAM::power (const REAL & x, int n)
Definition at line 1108 of file REALS.cc.
References iRRAM::REAL::square.
root()
REAL iRRAM::root (const REAL & x, int n)
Definition at line 32 of file sqrt.cc.
References iRRAM::approx(), iRRAM::bound(), iRRAM::limit(), iRRAM::lipschitz(), MP_mv_sqrt, iRRAM::scale(), iRRAM::size(), iRRAM::sqrt(), and iRRAM::DYADIC::value.
Referenced by iRRAM::round().
sign()
int iRRAM::sign (const RATIONAL & x)
Definition at line 139 of file RATIONAL.cc.
References MP_rat_sign.
Referenced by rat_gmp_power(), and iRRAM::strtoREAL().
sqrt() [1/3]
COMPLEX iRRAM::sqrt (const COMPLEX & z)
Definition at line 133 of file COMPLEX.cc.
References iRRAM::limit_mv().
Referenced by iRRAM::abs(), iRRAM::acos(), iRRAM::acosh(), iRRAM::asin(), iRRAM::asinh(), iRRAM::csqrt(), iRRAM::euler(), iRRAM::ln2(), iRRAM::log(), iRRAM::root(), iRRAM::COMPLEX::seterror(), iRRAM::sizetype_sqrt(), and iRRAM::tan().
sqrt() [2/3]
REAL iRRAM::sqrt (const REAL & x)
Computes the square root of the argument x.
For domain \([A;B]\) with \(A>0\), the square root function \(f=\sqrt{}\) has a Lipschitz bound:
\[ \forall x,y\in[A;B]: |f(x)-f(y)| \leq K\cdot|x-y| = K\cdot|f(x)+f(y)|\cdot|f(x)-f(y)| \Longleftrightarrow 1/|f(x)+f(y)| \leq K \]
Since \(\max_{x,y \in [A;B]} 1/|f(x)+f(y)| = 1/|2f(A)|\leq K\) for the function's argument \(x\in[x_c\pm x_\varepsilon]\) the error therefore is \(|f(x_c)-f(x)| \leq K|x-x_c| < Kx_\varepsilon \leq x_\varepsilon/(\sqrt{\check x}+\sqrt{\check x-x_\varepsilon}) < x_\varepsilon/(2\sqrt{\check x-x_\varepsilon})\).
This case, \(x\geq A=\check x-x_\varepsilon>0\), is chosen when \(\check x\geq 4x_\varepsilon\Longrightarrow |x|\geq 3x_\varepsilon\), therefore \(|\sqrt{x_c}-\sqrt x| \leq x_\varepsilon/(2\sqrt{\check x-x_\varepsilon})\). The absolute precision used to compute \(\sqrt{x_c}\) is \(\max\{P,e[z]\}\) where \(z\geq x_\varepsilon/(2\sqrt{\check x-x_\varepsilon})\) and \(e[v]=e\) for any sizetype representation \(m\cdot2^e\) of \(v\). The relative precision is \(\max\{e[\check x]+P,e[z]\}\).
Otherwise, \(x=0\) or \(4x_\varepsilon\geq\check x=\hat x-2^e>\hat x\cdot(1-2^{-32})\), then \(\sqrt{|x|} <\sqrt{\hat x+x_\varepsilon} <\sqrt{4x_\varepsilon/(1-2^{-32})+x_\varepsilon} <2.25\sqrt{x_\varepsilon}\) and \(0\approx\sqrt{|x|}\) is chosen as an approximation with error \(\geq3\sqrt{x_\varepsilon}\).
Todo:
For \(0\in[x_c\pm x_\varepsilon]\) use \(\approx[\sqrt{x_\varepsilon}\pm\sqrt{x_\varepsilon}] \) as result to decrease the error and disable representation of non-co-domain values smaller than zero.
Todo:
To determine \(0\notin[x_c\pm x_\varepsilon]\) check \(\check x\geq cx_\varepsilon\) with \(c\in\{2,3\} \) for tighter error bounds in both cases.
Todo:
In case \(0\notin[x_c\pm x_\varepsilon]\), does it make sense to use the bound \(x_\varepsilon/(\sqrt{\check x}+\sqrt{\check x-x_\varepsilon}) \) instead of \(x_\varepsilon/(2\sqrt{\check x-x_\varepsilon})\)?
Parameters
x non-negative real number
Returns
sqrt(x)
Definition at line 135 of file sqrt.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::getsize(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::max(), MP_init, MP_int_to_mp, MP_mv_sqrt, MP_type, iRRAM::ITERATION_DATA::prec_policy, iRRAM::sizetype_add_power2(), iRRAM::sizetype_dec(), iRRAM::sizetype_div(), iRRAM::sizetype_half(), iRRAM::sizetype_less(), iRRAM::sizetype_sqrt(), iRRAM::state, iRRAM::REAL::value, and iRRAM::REAL::vsize.
sqrt() [3/3]
INTEGER iRRAM::sqrt (const INTEGER & x) inline
Definition at line 434 of file INTEGER.h.
References MP_int_init, MP_int_sqrt, and MP_int_type.