iRRAM: Limit operations
Limit operations
Mathematical functions
Functions
REAL iRRAM::limit_lip (REAL(*f)(int, const REAL &), int lip_value, bool(*on_domain)(const REAL &), const REAL &x)
REAL iRRAM::limit_lip (REAL(*f)(int, const REAL &), int(*lip_bound)(const REAL &), const REAL &x)
REAL iRRAM::limit_lip (REAL(*f)(int, const REAL &, const REAL &), int lip, bool(*on_domain)(const REAL &, const REAL &), const REAL &x, const REAL &y)
REAL iRRAM::lipschitz (REAL(*f)(const REAL &), int lip, bool(*on_domain)(const REAL &), const REAL &x)
REAL iRRAM::lipschitz (REAL(*f)(const REAL &), REAL(*lip_f)(const REAL &), bool(*on_domain)(const REAL &), const REAL &x)
REAL iRRAM::lipschitz (REAL(*f)(const REAL &), REAL(*lip_f)(const REAL &), const REAL &x)
REAL iRRAM::lipschitz (REAL(*f)(int, const REAL &), int lip, bool(*on_domain)(int k, const REAL &), int k, const REAL &x)
REAL iRRAM::lipschitz (REAL(*f)(const REAL &, const REAL &), int lip, bool(*on_domain)(const REAL &, const REAL &), const REAL &x, const REAL &y)
REAL iRRAM::lipschitz (REAL(*f)(int, const REAL &, const REAL &), int lip, bool(*on_domain)(int k, const REAL &, const REAL &), int k, const REAL &x, const REAL &y)
REAL iRRAM::limit_hint (REAL(*f)(int, const REAL &), int hint, const REAL &x)
REAL iRRAM::limit_hint (REAL(*f)(int, const REAL &, const REAL &), int hint, const REAL &x, const REAL &y)
REALMATRIX iRRAM::limit_lip (REALMATRIX(*f)(int, const REALMATRIX &), int lip, bool(*on_domain)(const REALMATRIX &), const REALMATRIX &x)
REAL iRRAM::iteration (void(*f)(REAL &, REAL &, const int &param), const REAL &l, const REAL &r, const int &param)
REAL iRRAM::limit (const FUNCTION< REAL, int > &f)
template<typename F , typename... ContArgs>
auto iRRAM::limit (F f, const ContArgs &...cont_args) -> typename std::enable_if< any_continuous< ContArgs... >::value, decltype(f(0, cont_args...))>::type
Continuous variant of the limit operator.
template<typename F , typename... DiscArgs>
auto iRRAM::limit (F f, const DiscArgs &...disc_args) -> typename std::enable_if<!any_continuous< DiscArgs... >::value, decltype(f(0, disc_args...))>::type
template<class ARGUMENT , class RESULT >
RESULT iRRAM::limit_mv (RESULT(*f)(int prec, int *choice, const ARGUMENT &), const ARGUMENT &x)
template<class ARGUMENT , class DISCRETE , class RESULT >
RESULT iRRAM::limit_lip (RESULT(*f)(int, const ARGUMENT &, DISCRETE param), int lip_value, bool(*on_domain)(const ARGUMENT &), const ARGUMENT &x, DISCRETE param)
template<class CONT_ARGUMENT , class DISCRETE_ARGUMENT , class RESULT , class PARAM >
RESULT iRRAM::lipschitz_1p_1a (RESULT(*f)(const DISCRETE_ARGUMENT &, const PARAM &param), int lip, bool(*on_domain)(const CONT_ARGUMENT &, const PARAM &param), const CONT_ARGUMENT &x, const PARAM &param)
REAL iRRAM::limit (FUNCTION< REAL, int > f)
template REAL iRRAM::limit (REAL(*f)(int))
template REAL iRRAM::limit (REAL(*f)(int, const REAL &), const REAL &)
template REAL iRRAM::limit (REAL(*)(int, const REAL &, const REAL &), const REAL &, const REAL &)
template REAL iRRAM::limit (REAL(*)(int, const REAL &, int), const REAL &, const int &)
template COMPLEX iRRAM::limit (COMPLEX(*)(int, COMPLEX const &), const COMPLEX &)
template REALMATRIX iRRAM::limit (REALMATRIX(*)(int, const REALMATRIX &), const REALMATRIX &)
Detailed Description
Limit operations
These functions compute the mathematical limit \(y\) of sequences \(f_p\) of continuous objects, optionally depending on discrete or continuous arguments \(x\) satisfying
\[\forall p\in\mathbb{Z} : \Vert f_p(x)-y\Vert_\infty < 2^p\]
in the iRRAM limit for \(x, f_p\) and \(y\). In the first case, \(x\) is discrete and therefore exact, the errors introduced stem from imprecision of the computation \(f_p\) itself, which is unbounded. Since \(f_p\) is executed within iRRAM, its mathematical operations are exact within \(2^q\), where \(q\) is the current working precision, however the objects operated upon are imprecise intervals and therefore \(f_p\) introduces additional errors. To reduce their effect, the current working precision \(q\) is successively increased, starting at the initial \(P\) when limit was invoked (env.saved_prec()), whenever \(f_q\) could not be computed. If at some point the computation \(f_q\) succeeds, it has computed \(y\) up to \(2^q < 2^p\). The error \(2^p\) is added to \(y\)'s error to ensure correctness.
If \(x\) is not exact, \(|f_p(x)-y|\) generally is larger than \(2^p\). This additional error cannot get arbitrarily small when increasing \(p\), therefore a different scheme is employed: when computing \(f_P(x)\) failed and also \(f_{p_0}(x)\) failed (where \(p_0\) is the lowest precision available in iRRAM), the limit cannot be computed with the current precision of \(x\) and therefore a reiteration is done. If \(f_P(x)\) succeeded but the resulting error \({}+ 2^P\) is larger than \(2^{P[-1]}\) and is larger than \(x\)'s error \({}- 2^{P[-1]}\), then \(p\) is set to \(p_0\) for the potential next iteration. If \(y\)'s error already is smaller than \(2^P\), the iteration succeeded. Otherwise the result is deemed too imprecise and the computation is repeated with \(p\) increased by 4 precision steps.
Note
There fundamentally are two different variants of limit(), one taking only parameters representing discrete values and one for the mixed/only-continuous case. Continuity of a type is determined through specializations of the type trait
template <typename T> struct is_continuous;
providing a static bool value as defined in <iRRAM/lib.h>.
Which one is called when invoking limit(f,args...) is not determined by the actual parameter types of f but by the types of args... This is deliberate and consistent with how iRRAM works - i.e. allowing implicit conversions from the types of smaller domain to those with larger domain. Usually there is no need to explicitely specify the template types.
Example:
REAL f(int prec, const REAL &x);
REAL y = limit(f, 42)
will not invoke the continuous variant since a REAL will be constructed from the given int using REAL's implicit converting constructor while limit() is being executed. That REAL's precision therefore is controlled by limit() and being adjusted as to f's and limit's requirements to yield a precise enough result.
This behaviour is desirable as the non-continuous parameter version of limit() is more efficient.
Regarding the same example but calling
REAL x = 42; // or a complicated computation
REAL y = limit(f, x);
explains the necessity for the second version. It will use the continuous version as the precision of the result of f(p,x) typically will depend on the precision of x and not just on p. Therefore the continuous variant of limit() provisions for reiterations outside of the limit() call to enable increased precision of x itself.
For a continuous parameter pack T (as determined by any_continuous<T...>) a function
int geterror_exp(const T &...)
needs to be provided which defaults to returning the maximum error exponent as determined by
int geterror_exp(const Ti &t)
the default implementation of which is
return geterror(t).exponent;
but may be specialized according to the type's characteristics. In the future it is possible that the continuous variant of limit() will use more fine-grained error information than just the exponent, so it may be helpful to additionally provide
sizetype geterror(const Ti &)
for all continuous types Ti used as limit() parameters. Additionally, declarations of
void     seterror(R &, sizetype)
sizetype geterror(const R &)
for result type R must be provided for both of the limit() variants. For iRRAM's types REAL, *REALMATRIX and COMPLEX implementations are available.
Function Documentation
REAL iRRAM::iteration (void(*)(REAL &, REAL &, const int &param) f, const REAL & l, const REAL & r, const int & param)
Definition at line 597 of file limits.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM::REAL::getsize(), iRRAM::stiff::inc_step(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::stiff::saved_prec(), iRRAM::scale(), iRRAM::REAL::seterror(), iRRAM::sizetype_exact(), iRRAM::sizetype_half(), and iRRAM::state.
Referenced by iRRAM::lipschitz_1p_1a().
template<typename F , typename... ContArgs> auto iRRAM::limit (F f, const ContArgs &... cont_args) -> typename std::enable_if<any_continuous<ContArgs...>::value, decltype(f(0,cont_args...))>::type
Continuous variant of the limit operator.
Parameters
[in] f functional object of signature Result (int prec, const ContArgs &...)
[in] cont_args the mixed- or continuous arguments to be passed when invoking f
Definition at line 224 of file limit_templates.h.
References iRRAM::generic_sizetype< M, E >::exponent, iRRAM::geterror_exp(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::iRRAM_prec_array, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::stiff::saved_prec(), iRRAM::stiff::saved_step(), iRRAM::sizetype_add_power2(), and iRRAM::sizetype_less().
template<typename F , typename... DiscArgs> auto iRRAM::limit (F f, const DiscArgs &... disc_args) -> typename std::enable_if<!any_continuous<DiscArgs...>::value, decltype(f(0,disc_args...))>::type
Definition at line 297 of file limit_templates.h.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::stiff::inc_step(), iRRAM_DEBUG2, iRRAM::limit_debug(), iRRAM::limit_debug2(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::stiff::saved_prec(), iRRAM::sizetype_add_power2(), and iRRAM::state.
REAL iRRAM::limit (FUNCTION< REAL, int > f)
template REAL iRRAM::limit (REAL(*)(int, const REAL &) f, const REAL &)
template COMPLEX iRRAM::limit (COMPLEX(*)(int, COMPLEX const &) , const COMPLEX &)
REAL iRRAM::limit (const FUNCTION< REAL, int > & f)
Definition at line 664 of file limits.cc.
References iRRAM::cerr, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG0, iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::iRRAM_prec_array, iRRAM::limit_debug(), iRRAM::limit_mv< COMPLEX, COMPLEX >(), iRRAM::limit_mv< REALMATRIX, REALMATRIX >(), iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::stiff::saved_prec(), iRRAM::stiff::saved_step(), iRRAM::REAL::seterror(), iRRAM::sizetype_add_power2(), and iRRAM::sizetype_less().
Referenced by iRRAM::euler(), iRRAM::lipschitz_1p_1a(), iRRAM::ln2(), iRRAM::operator!(), iRRAM::pi(), and iRRAM::root().
template REAL iRRAM::limit (REAL(*)(int, const REAL &, const REAL &) , const REAL & , const REAL &)
template REALMATRIX iRRAM::limit (REALMATRIX(*)(int, const REALMATRIX &) , const REALMATRIX &)
template REAL iRRAM::limit (REAL(*)(int) f)
template REAL iRRAM::limit (REAL(*)(int, const REAL &, int) , const REAL & , const int &)
REAL iRRAM::limit_hint (REAL(*)(int, const REAL &) f, int hint, const REAL & x)
Definition at line 390 of file limits.cc.
References iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::iRRAM_prec_array, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::max(), REITERATE, iRRAM::stiff::saved_prec(), iRRAM::REAL::seterror(), iRRAM::sizetype_add_power2(), and iRRAM::sizetype_less().
Referenced by iRRAM::lipschitz_1p_1a().
REAL iRRAM::limit_hint (REAL(*)(int, const REAL &, const REAL &) f, int hint, const REAL & x, const REAL & y)
Definition at line 439 of file limits.cc.
References iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::iRRAM_prec_array, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::max(), REITERATE, iRRAM::stiff::saved_prec(), iRRAM::REAL::seterror(), iRRAM::sizetype_add_power2(), and iRRAM::sizetype_less().
REAL iRRAM::limit_lip (REAL(*)(int, const REAL &) f, int lip_value, bool(*)(const REAL &) on_domain, const REAL & x)
Definition at line 45 of file limits.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM::stiff::inc_step(), iRRAM_DEBUG2, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::stiff::saved_prec(), iRRAM::sizetype_add_power2(), iRRAM::sizetype_exact(), iRRAM::state, and iRRAM::REAL::value.
Referenced by iRRAM::atan(), iRRAM::cos(), iRRAM::exp(), iRRAM::log(), iRRAM::sin(), and iRRAM::tan().
REAL iRRAM::limit_lip (REAL(*)(int, const REAL &) f, int(*)(const REAL &) lip_bound, const REAL & x)
Definition at line 88 of file limits.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM::stiff::inc_step(), iRRAM_DEBUG2, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::stiff::saved_prec(), iRRAM::sizetype_add_power2(), iRRAM::sizetype_exact(), iRRAM::state, and iRRAM::REAL::value.
REAL iRRAM::limit_lip (REAL(*)(int, const REAL &, const REAL &) f, int lip, bool(*)(const REAL &, const REAL &) on_domain, const REAL & x, const REAL & y)
Definition at line 134 of file limits.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM::stiff::inc_step(), iRRAM_DEBUG2, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::stiff::saved_prec(), iRRAM::sizetype_add_power2(), iRRAM::sizetype_exact(), iRRAM::state, and iRRAM::REAL::value.
template<class ARGUMENT , class DISCRETE , class RESULT > RESULT iRRAM::limit_lip (RESULT(*)(int, const ARGUMENT &, DISCRETE param) f, int lip_value, bool(*)(const ARGUMENT &) on_domain, const ARGUMENT & x, DISCRETE param)
Definition at line 406 of file limit_templates.h.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::stiff::inc_step(), iRRAM_DEBUG0, iRRAM_DEBUG2, iRRAM::limit_debug(), iRRAM::limit_debug2(), iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::stiff::saved_prec(), iRRAM::sizetype_exact(), iRRAM::sizetype_power2(), and iRRAM::state.
REALMATRIX iRRAM::limit_lip (REALMATRIX(*)(int, const REALMATRIX &) f, int lip, bool(*)(const REALMATRIX &) on_domain, const REALMATRIX & x)
Definition at line 488 of file limits.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REALMATRIX::adderror(), iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REALMATRIX::geterror(), iRRAM::stiff::inc_step(), iRRAM_DEBUG0, iRRAM_DEBUG2, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::stiff::saved_prec(), iRRAM::REALMATRIX::seterror(), iRRAM::sizetype_exact(), and iRRAM::state.
template<class ARGUMENT , class RESULT > RESULT iRRAM::limit_mv (RESULT(*)(int prec, int *choice, const ARGUMENT &) f, const ARGUMENT & x)
Definition at line 330 of file limit_templates.h.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::iRRAM_thread_data_class::cache_i, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG0, iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::iRRAM_prec_array, iRRAM::limit_debug(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::iRRAM_cache< DATA >::modify(), iRRAM::iRRAM_cache< DATA >::put(), REITERATE, iRRAM::stiff::saved_prec(), iRRAM::stiff::saved_step(), iRRAM::sizetype_less(), iRRAM::sizetype_power2(), iRRAM::state, and iRRAM::state_t::thread_data_address.
Referenced by iRRAM::sqrt().
REAL iRRAM::lipschitz (REAL(*)(const REAL &) f, int lip, bool(*)(const REAL &) on_domain, const REAL & x)
Definition at line 178 of file limits.cc.
References iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::sizetype_exact(), and iRRAM::REAL::value.
Referenced by iRRAM::root().
REAL iRRAM::lipschitz (REAL(*)(const REAL &) f, REAL(*)(const REAL &) lip_f, bool(*)(const REAL &) on_domain, const REAL & x)
Definition at line 207 of file limits.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM::REAL::getsize(), iRRAM::stiff::inc_step(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::sizetype_exact(), iRRAM::state, and iRRAM::REAL::value.
REAL iRRAM::lipschitz (REAL(*)(const REAL &) f, REAL(*)(const REAL &) lip_f, const REAL & x)
Definition at line 254 of file limits.cc.
References iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM::REAL::getsize(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::sizetype_exact(), and iRRAM::REAL::value.
REAL iRRAM::lipschitz (REAL(*)(int, const REAL &) f, int lip, bool(*)(int k, const REAL &) on_domain, int k, const REAL & x)
Definition at line 288 of file limits.cc.
References iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::sizetype_exact(), and iRRAM::REAL::value.
REAL iRRAM::lipschitz (REAL(*)(const REAL &, const REAL &) f, int lip, bool(*)(const REAL &, const REAL &) on_domain, const REAL & x, const REAL & y)
Definition at line 317 of file limits.cc.
References iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::sizetype_exact(), and iRRAM::REAL::value.
REAL iRRAM::lipschitz (REAL(*)(int, const REAL &, const REAL &) f, int lip, bool(*)(int k, const REAL &, const REAL &) on_domain, int k, const REAL & x, const REAL & y)
Definition at line 352 of file limits.cc.
References iRRAM::REAL::adderror(), iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::REAL::geterror(), iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, REITERATE, iRRAM::sizetype_exact(), and iRRAM::REAL::value.
template<class CONT_ARGUMENT , class DISCRETE_ARGUMENT , class RESULT , class PARAM > RESULT iRRAM::lipschitz_1p_1a (RESULT(*)(const DISCRETE_ARGUMENT &, const PARAM &param) f, int lip, bool(*)(const CONT_ARGUMENT &, const PARAM &param) on_domain, const CONT_ARGUMENT & x, const PARAM & param)
Definition at line 521 of file limit_templates.h.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::stiff::inc_step(), iRRAM_DEBUG0, iRRAM_DEBUG1, iRRAM_DEBUG2, iRRAM::iteration(), iRRAM::limit(), iRRAM::limit_hint(), iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::ITERATION_DATA::prec_step, REITERATE, and iRRAM::state.