iRRAM: include/iRRAM.h File Reference
iRRAM.h File Reference
#include <iRRAM/lib.h>
Functions
void compute (void)
int main (int argc, char **argv)
Function Documentation
compute()
void compute (void)
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 34 of file iRRAM.h.
References compute(), iRRAM::exec(), and iRRAM_initialize2().