iRRAM: src/MPFR/mpfr_extension.cc File Reference
mpfr_extension.cc File Reference
#include <iRRAM/lib.h>
#include <iRRAM/mpfr_extension.h>
Macros
#define MPFR_PREC(x) ((x)->_mpfr_prec)
#define MPFR_SIZE(x) ((MPFR_PREC(x)-1)/BITS_PER_MP_LIMB+1)
#define MPFR_EXP(x) ((x)->_mpfr_exp)
#define MPFR_MANT(x) ((x)->_mpfr_d)
Typedefs
typedef DYADIC(DYADIC_function) (const DYADIC &, const int &)
Functions
void mpfr_wrapper (DYADIC_function f, mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_test (mpfr_ptr y, mpfr_srcptr u, int p, mp_rnd_t rnd_mode)
void mpfr_ext_exp (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_log (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_sin (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_cos (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_tan (mpfr_ptr r, mpfr_srcptr u, int p)
Macro Definition Documentation
MPFR_EXP
#define MPFR_EXP (x) ((x)->_mpfr_exp)
Definition at line 30 of file mpfr_extension.cc.
MPFR_MANT
#define MPFR_MANT (x) ((x)->_mpfr_d)
Definition at line 31 of file mpfr_extension.cc.
MPFR_PREC
#define MPFR_PREC (x) ((x)->_mpfr_prec)
Definition at line 28 of file mpfr_extension.cc.
MPFR_SIZE
#define MPFR_SIZE (x) ((MPFR_PREC(x)-1)/BITS_PER_MP_LIMB+1)
Definition at line 29 of file mpfr_extension.cc.
Typedef Documentation
DYADIC_function
typedef DYADIC(DYADIC_function) (const DYADIC &, const int &)
Definition at line 35 of file mpfr_extension.cc.
Function Documentation
mpfr_ext_cos()
void mpfr_ext_cos (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 76 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_exp()
void mpfr_ext_exp (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 67 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_log()
void mpfr_ext_log (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 70 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_sin()
void mpfr_ext_sin (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 73 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_tan()
void mpfr_ext_tan (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 79 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_test()
void mpfr_ext_test (mpfr_ptr y, mpfr_srcptr u, int p, mp_rnd_t rnd_mode)
Definition at line 49 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_wrapper()
void mpfr_wrapper (DYADIC_function f, mpfr_ptr r, mpfr_srcptr u, int p) inline
Definition at line 37 of file mpfr_extension.cc.
References iRRAM::arg(), iRRAM::exec(), and iRRAM::DYADIC::value.
Referenced by mpfr_ext_cos(), mpfr_ext_exp(), mpfr_ext_log(), mpfr_ext_sin(), mpfr_ext_tan(), and mpfr_ext_test().