iRRAM: iRRAM Namespace Reference
iRRAM Namespace Reference
Classes
struct _SetRflags
struct _SetRwidth
class cachelist
class COMPLEX
struct conditional_comparison_overloads
struct disjunction
struct disjunction< C, D... >
class DYADIC
class DYADIC_precision
class FUNCTION
class FUNCTIONAL_algorithm
class FUNCTIONAL_object
class FUNCTIONAL_value
struct generic_sizetype
struct get_type
struct get_type< bool >
struct get_type< MP_int_type >
struct get_type< MP_type >
class INTEGER
class INTERVAL
class iRRAM_cache
class iRRAM_cache_type
struct iRRAM_Numerical_Exception
class iRRAM_thread_data_class
class irstream
struct is_continuous
struct is_continuous< C & >
struct is_continuous< C && >
struct is_continuous< COMPLEX >
struct is_continuous< const C & >
struct is_continuous< FUNCTION< REAL, Args... > >
struct is_continuous< INTERVAL >
struct is_continuous< REAL >
struct is_continuous< REALMATRIX >
struct is_continuous< SPARSEREALMATRIX >
struct Iteration
struct ITERATION_DATA
class LAZY_BOOLEAN
struct limit_computation
Combination of stiff and single_valued.
struct negation
class orstream
class precision_mode
Switch the precision policy to absolute or relative precision.
class RATIONAL
class REAL
class REALMATRIX
struct relaxed
Temporarily halve the working precision.
class rstream
struct single_valued
Explicit declaration of single_valued behaviour of a code section despite multi-valued operations.
class SPARSEREALMATRIX
class SPM_ELEMENT
struct state_t
class stiff
Temporary increase of the working precision.
struct wrap_type
Typedefs
typedef generic_sizetype< unsigned int, int > sizetype
template<typename Base , typename EquivBase , typename Compat , typename Ret = Base>
using enable_if_compat = typename std::enable_if< std::is_same< typename std::remove_cv< EquivBase >::type, typename std::remove_cv< Base >::type >::value &&std::is_convertible< Compat, Base >::value,Ret >::type
template<typename... T>
using conjunction = negation< disjunction< negation< T >... >>
template<typename... T>
using any_continuous = disjunction< is_continuous< T >... >
Enumerations
enum float_form : int { float_form::absolute, float_form::relative, float_form::show }
Functions
COMPLEX operator+ (const COMPLEX &x, const COMPLEX &y)
COMPLEX operator- (const COMPLEX &x, const COMPLEX &y)
COMPLEX operator- (const COMPLEX &x)
COMPLEX operator* (const COMPLEX &x, const COMPLEX &y)
COMPLEX operator/ (const COMPLEX &x, const COMPLEX &y)
REAL real (const COMPLEX &z)
REAL imag (const COMPLEX &z)
REAL abs (const COMPLEX &z)
COMPLEX sqrt (const COMPLEX &z)
COMPLEX csqrt (const COMPLEX &z)
REAL arg (const COMPLEX &z)
COMPLEX log (const COMPLEX &z)
COMPLEX exp (const COMPLEX &z)
COMPLEX sin (const COMPLEX &z)
COMPLEX cos (const COMPLEX &z)
COMPLEX tan (const COMPLEX &z)
COMPLEX cotan (const COMPLEX &z)
COMPLEX cosec (const COMPLEX &z)
COMPLEX sec (const COMPLEX &z)
COMPLEX sinh (const COMPLEX &z)
COMPLEX cosh (const COMPLEX &z)
COMPLEX tanh (const COMPLEX &z)
COMPLEX coth (const COMPLEX &z)
COMPLEX sech (const COMPLEX &z)
COMPLEX cosech (const COMPLEX &z)
COMPLEX asin (const COMPLEX &z)
COMPLEX acos (const COMPLEX &z)
COMPLEX atan (const COMPLEX &z)
COMPLEX acotan (const COMPLEX &z)
COMPLEX asec (const COMPLEX &z)
COMPLEX acosec (const COMPLEX &z)
COMPLEX asinh (const COMPLEX &z)
COMPLEX acosh (const COMPLEX &z)
COMPLEX atanh (const COMPLEX &z)
COMPLEX acoth (const COMPLEX &z)
COMPLEX asech (const COMPLEX &z)
COMPLEX acosech (const COMPLEX &z)
DYADIC ADD (const DYADIC &x, const DYADIC &y, const int p)
DYADIC SUB (const DYADIC &x, const DYADIC &y, const int p)
DYADIC MULT (const DYADIC &x, const DYADIC &y, const int p)
DYADIC DIV (const DYADIC &x, const DYADIC &y, const int p)
DYADIC scale (const DYADIC &x, const int n)
bool operator< (const DYADIC &x, const DYADIC &y)
bool operator> (const DYADIC &x, const DYADIC &y)
bool operator<= (const DYADIC &x, const DYADIC &y)
bool operator>= (const DYADIC &x, const DYADIC &y)
bool operator== (const DYADIC &x, const DYADIC &y)
bool operator!= (const DYADIC &x, const DYADIC &y)
std::string swrite (const DYADIC &x, const int w)
int size (const DYADIC &x)
DYADIC abs (const DYADIC &x)
REAL exp (const REAL &x)
REAL euler ()
REAL log (const REAL &x)
INTERVAL & operator+= (INTERVAL &x, const INTERVAL &y)
INTERVAL & operator-= (INTERVAL &x, const INTERVAL &y)
INTERVAL operator- (const INTERVAL &x)
INTERVAL operator* (const INTERVAL &x, const INTERVAL &y)
INTERVAL operator/ (const INTERVAL &x, const INTERVAL &y)
REAL wid (const INTERVAL &x)
REAL inf (const INTERVAL &x)
REAL sup (const INTERVAL &x)
REAL mid (const INTERVAL &x)
REAL mag (const INTERVAL &x)
REAL mig (const INTERVAL &x)
INTERVAL fabs (const INTERVAL &x)
INTERVAL square (const INTERVAL &x)
INTERVAL power (const INTERVAL &x, int n)
INTERVAL exp (const INTERVAL &x)
INTERVAL log (const INTERVAL &x)
INTERVAL sin (const INTERVAL &x)
INTERVAL cos (const INTERVAL &x)
INTERVAL tan (const INTERVAL &x)
INTERVAL asin (const INTERVAL &x)
INTERVAL acos (const INTERVAL &x)
INTERVAL atan (const INTERVAL &x)
LAZY_BOOLEAN superset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN proper_superset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN subset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN proper_subset (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN in_interior (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN disjoint (const INTERVAL &x, const INTERVAL &y)
LAZY_BOOLEAN in (const REAL &x, const INTERVAL &y)
INTERVAL interval_hull (const INTERVAL &x, const INTERVAL &y)
INTERVAL intersect (const INTERVAL &x, const INTERVAL &y)
int check (const LAZY_BOOLEAN &lb)
int choose (const LAZY_BOOLEAN &x1, const LAZY_BOOLEAN &x2, const LAZY_BOOLEAN &x3, const LAZY_BOOLEAN &x4, const LAZY_BOOLEAN &x5, const LAZY_BOOLEAN &x6)
LAZY_BOOLEAN operator&& (const LAZY_BOOLEAN &x, const LAZY_BOOLEAN &y) noexcept
LAZY_BOOLEAN operator|| (const LAZY_BOOLEAN &x, const LAZY_BOOLEAN &y) noexcept
LAZY_BOOLEAN operator! (const LAZY_BOOLEAN &x) noexcept
REAL limit_lip (REAL(*f)(int, const REAL &), int lip_value, bool(*on_domain)(const REAL &), const REAL &x)
REAL limit_lip (REAL(*f)(int, const REAL &), int(*lip_bound)(const REAL &), const REAL &x)
REAL limit_lip (REAL(*f)(int, const REAL &, const REAL &), int lip, bool(*on_domain)(const REAL &, const REAL &), const REAL &x, const REAL &y)
REAL lipschitz (REAL(*f)(const REAL &), int lip, bool(*on_domain)(const REAL &), const REAL &x)
REAL lipschitz (REAL(*f)(const REAL &), REAL(*lip_f)(const REAL &), bool(*on_domain)(const REAL &), const REAL &x)
REAL lipschitz (REAL(*f)(const REAL &), REAL(*lip_f)(const REAL &), const REAL &x)
REAL lipschitz (REAL(*f)(int, const REAL &), int lip, bool(*on_domain)(int k, const REAL &), int k, const REAL &x)
REAL lipschitz (REAL(*f)(const REAL &, const REAL &), int lip, bool(*on_domain)(const REAL &, const REAL &), const REAL &x, const REAL &y)
REAL lipschitz (REAL(*f)(int, const REAL &, const REAL &), int lip, bool(*on_domain)(int k, const REAL &, const REAL &), int k, const REAL &x, const REAL &y)
REAL limit_hint (REAL(*f)(int, const REAL &), int hint, const REAL &x)
REAL limit_hint (REAL(*f)(int, const REAL &, const REAL &), int hint, const REAL &x, const REAL &y)
REALMATRIX limit_lip (REALMATRIX(*f)(int, const REALMATRIX &), int lip, bool(*on_domain)(const REALMATRIX &), const REALMATRIX &x)
REAL iteration (void(*f)(REAL &, REAL &, const int &param), const REAL &l, const REAL &r, const int &param)
REAL limit (const FUNCTION< REAL, int > &f)
template COMPLEX limit_mv< COMPLEX, COMPLEX > (COMPLEX(*)(int, int *, COMPLEX const &), COMPLEX const &)
template REALMATRIX limit_mv< REALMATRIX, REALMATRIX > (REALMATRIX(*)(int, int *, REALMATRIX const &), REALMATRIX const &)
template REAL limit (REAL(*)(int, REAL const &), REAL const &)
template REAL limit (REAL(*)(int, const REAL &, const REAL &), const REAL &, const REAL &)
template COMPLEX limit (COMPLEX(*)(int, const COMPLEX &), COMPLEX const &)
template REALMATRIX limit (REALMATRIX(*)(int, const REALMATRIX &), const REALMATRIX &)
template REAL limit (REAL(*f)(int))
template REAL limit (REAL(*)(int, const REAL &, int), const REAL &, const int &)
REAL ln2 ()
REAL pi ()
int sign (const RATIONAL &x)
RATIONAL scale (RATIONAL x, int n)
RATIONAL & operator+= (RATIONAL &x, const RATIONAL &y)
RATIONAL & operator+= (RATIONAL &x, int y)
RATIONAL operator- (int x, RATIONAL y)
RATIONAL & operator-= (RATIONAL &x, const RATIONAL &y)
RATIONAL operator- (RATIONAL x)
RATIONAL & operator*= (RATIONAL &x, const RATIONAL &y)
RATIONAL & operator*= (RATIONAL &x, const int n)
RATIONAL operator/ (int x, RATIONAL y)
RATIONAL & operator/= (RATIONAL &x, const RATIONAL &y)
RATIONAL & operator/= (RATIONAL &x, const int n)
RATIONAL abs (RATIONAL x)
INTEGER denominator (const RATIONAL &x)
INTEGER numerator (const RATIONAL &x)
bool operator< (const RATIONAL &x, const RATIONAL &y)
bool operator== (const RATIONAL &x, const RATIONAL &y)
std::string swrite (const RATIONAL &x, const int w)
std::string swrite (const RATIONAL &x)
void resources (double &time, unsigned int &memory)
void show_statistics ()
REALMATRIX eye (unsigned int rows)
REALMATRIX zeroes (unsigned int rows, unsigned int columns)
REALMATRIX ones (unsigned int rows, unsigned int columns)
REALMATRIX operator+ (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator- (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator* (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX operator/ (const REALMATRIX &x, const REALMATRIX &y)
REALMATRIX solve (REALMATRIX &lside, REALMATRIX &rside, int use_pivot)
REALMATRIX operator* (const REALMATRIX &x, const REAL &y)
REALMATRIX operator/ (const REALMATRIX &x, const REAL &y)
int bound (const REALMATRIX &x, const int k)
REAL maxnorm (const REALMATRIX &x)
REAL rowsumnorm (const REALMATRIX &x)
REAL colsumnorm (const REALMATRIX &x)
REALMATRIX exp (const REALMATRIX &x)
REALMATRIX steady_state (const REALMATRIX &x)
REALMATRIX steady_state (const SPARSEREALMATRIX &x)
REALMATRIX equilib (const SPARSEREALMATRIX &x)
void equilib_del (SPARSEREALMATRIX &chain, REALMATRIX &result)
std::string swrite (const REAL &x, const int w, const float_form form)
void rwrite (const REAL &x, const int w)
void rwritee (const REAL &x, const int w)
void rshow (const REAL &x, const int w)
REAL scale (const REAL &x, int n)
LAZY_BOOLEAN positive (const REAL &x, int k)
DYADIC approx (const REAL &x, const int p)
Computes a dyadic approximation to x that is accurate to 2^p.
int size (const REAL &x)
Returns a tight bound to the logarithmic value of |x|: \(2^{k-2}-2^e\leq|x|<2^k\), where e is x.vsize.exponent.
int upperbound (const REAL &x)
LAZY_BOOLEAN bound (const REAL &x, const int k)
REAL strtoREAL2 (const char *s, char **endptr)
Converts a base-10 string in scientific notation to REAL.
REAL strtoREAL (const char *s, char **endptr)
REAL atoREAL (const char *s)
REAL modulo (const REAL &x, const REAL &y)
REAL power (const REAL &x, const REAL &y)
REAL power (const REAL &x, int n)
REAL maximum (const REAL &x, const REAL &y)
REAL minimum (const REAL &x, const REAL &y)
REAL abs (const std::vector< REAL > &x)
int module (REAL(*f)(const REAL &), const REAL &x, int p)
REAL cos (const REAL &x)
REAL sin (const REAL &x)
REAL tan (const REAL &x)
REAL atan (const REAL &x)
REAL asin (const REAL &x)
REAL acos (const REAL &x)
REAL asec (const REAL &x)
REAL acosec (const REAL &x)
REAL sec (const REAL &x)
REAL cosec (const REAL &x)
REAL cotan (const REAL &x)
REAL sech (const REAL &x)
REAL cosech (const REAL &x)
REAL sinh (const REAL &x)
REAL cosh (const REAL &x)
REAL tanh (const REAL &x)
REAL coth (const REAL &x)
REAL asinh (const REAL &x)
REAL acosh (const REAL &x)
REAL atanh (const REAL &x)
REAL acoth (const REAL &x)
REAL asech (const REAL &x)
REAL acosech (const REAL &x)
void sparse_set (SPARSEREALMATRIX &m, unsigned int i, unsigned int j, const REAL &x)
void sparse_unset (SPARSEREALMATRIX &m, unsigned int i, unsigned int j)
SPM_ELEMENT * sparse_get_ptr (SPARSEREALMATRIX &m, unsigned int i, unsigned int j)
SPARSEREALMATRIX sparse_eye (unsigned int rows)
SPARSEREALMATRIX sparse_zeroes (unsigned int rows, unsigned int columns)
SPARSEREALMATRIX sparse_ones (unsigned int rows, unsigned int columns)
SPARSEREALMATRIX operator+ (const SPARSEREALMATRIX &x, const SPARSEREALMATRIX &y)
SPARSEREALMATRIX operator- (const SPARSEREALMATRIX &x, const SPARSEREALMATRIX &y)
SPARSEREALMATRIX operator* (const SPARSEREALMATRIX &x, const SPARSEREALMATRIX &y)
SPARSEREALMATRIX operator/ (const SPARSEREALMATRIX &x, const SPARSEREALMATRIX &y)
SPARSEREALMATRIX solve (SPARSEREALMATRIX &lside, SPARSEREALMATRIX &rside, int use_pivot)
REAL maxnorm (const SPARSEREALMATRIX &x)
REAL rowsumnorm (const SPARSEREALMATRIX &x)
REAL colsumnorm (const SPARSEREALMATRIX &x)
REAL root (const REAL &x, int n)
REAL sqrt (const REAL &x)
bool operator! (orstream &x)
bool operator! (irstream &x)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > from_algorithm (RESULT(evalp)(const PARAM &...z))
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > from_algorithm (const std::function< RESULT(const PARAM &...)> &evalp)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > from_value (const RESULT &value)
template<class RESULT , class INTERMEDIATE , class... PARAM>
FUNCTION< RESULT, PARAM... > compose (const FUNCTION< RESULT, INTERMEDIATE > &outer, const FUNCTION< INTERMEDIATE, PARAM... > &inner)
template<class RESULT1 , class... PARAM1, class RESULT2 , class... PARAM2>
FUNCTION< std::pair< RESULT1, RESULT2 >, std::pair< PARAM1..., PARAM2... > > product (const FUNCTION< RESULT1, PARAM1... > &f_1, const FUNCTION< RESULT2, PARAM2... > &f_2)
template<class RESULT1 , class RESULT2 , class... PARAM>
FUNCTION< std::pair< RESULT1, RESULT2 >, PARAM... > juxtaposition (const FUNCTION< RESULT1, PARAM... > &f_1, const FUNCTION< RESULT2, PARAM... > &f_2)
template<class RESULT1 , class RESULT2 , class... PARAM>
FUNCTION< RESULT1, PARAM... > first (const FUNCTION< std::pair< RESULT1, RESULT2 >, PARAM... > &f)
template<class RESULT1 , class RESULT2 , class... PARAM>
FUNCTION< RESULT2, PARAM... > second (const FUNCTION< std::pair< RESULT1, RESULT2 >, PARAM... > &f)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > projection (const FUNCTION< std::vector< RESULT >, PARAM... > &f, const int i)
template<class PARAM >
FUNCTION< PARAM, PARAM > polynomial (const std::vector< PARAM > &coeff)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > addition (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > &a)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator+ (const FUNCTION< RESULT, PARAM... > &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > subtraction (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > &a)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator- (const FUNCTION< RESULT, PARAM... > &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > multiplication (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > &a)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator* (const FUNCTION< RESULT, PARAM... > &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > division (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > &a)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator/ (const FUNCTION< RESULT, PARAM... > &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator+ (const FUNCTION< RESULT, PARAM... > &a, const RESULT &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator+ (const RESULT &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator* (const FUNCTION< RESULT, PARAM... > &a, const RESULT &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator* (const RESULT &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator- (const FUNCTION< RESULT, PARAM... > &a, const RESULT &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator- (const RESULT &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator/ (const FUNCTION< RESULT, PARAM... > &a, const RESULT &b)
template<class RESULT , class... PARAM>
FUNCTION< RESULT, PARAM... > operator/ (const RESULT &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > less_than (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > &a)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator< (const FUNCTION< RESULT, PARAM... > &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator> (const FUNCTION< RESULT, PARAM... > &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator< (const FUNCTION< RESULT, PARAM... > &a, const RESULT &b)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator< (const RESULT &a, const FUNCTION< RESULT, PARAM... > &b)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator> (const FUNCTION< RESULT, PARAM... > &a, const RESULT &b)
template<class RESULT , class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator> (const RESULT &a, const FUNCTION< RESULT, PARAM... > &b)
template<class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > LAZY_BOOLEAN_FUNCTION_and (const FUNCTION< std::pair< LAZY_BOOLEAN, LAZY_BOOLEAN >, PARAM... > &a)
template<class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator&& (const FUNCTION< LAZY_BOOLEAN, PARAM... > &a, const FUNCTION< LAZY_BOOLEAN, PARAM... > &b)
template<class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > LAZY_BOOLEAN_FUNCTION_or (const FUNCTION< std::pair< LAZY_BOOLEAN, LAZY_BOOLEAN >, PARAM... > &a)
template<class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator|| (const FUNCTION< LAZY_BOOLEAN, PARAM... > &a, const FUNCTION< LAZY_BOOLEAN, PARAM... > &b)
template<class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > LAZY_BOOLEAN_FUNCTION_not (const FUNCTION< LAZY_BOOLEAN, PARAM... > &a)
template<class... PARAM>
FUNCTION< LAZY_BOOLEAN, PARAM... > operator! (const FUNCTION< LAZY_BOOLEAN, PARAM... > &a)
INTEGER scale (const INTEGER &x, const int n)
int sign (const INTEGER &x)
int size (const INTEGER &x)
INTEGER power (const INTEGER &x, unsigned n)
INTEGER operator<< (const INTEGER &x, const int n)
INTEGER operator>> (const INTEGER &x, const int n)
INTEGER operator+ (const INTEGER &x, const INTEGER &y)
INTEGER operator+ (const INTEGER &x, const int y)
INTEGER operator+ (const int x, const INTEGER &y)
INTEGER & operator+= (INTEGER &x, const INTEGER &y)
INTEGER & operator+= (INTEGER &x, int n)
INTEGER operator- (const INTEGER &x, const INTEGER &y)
INTEGER operator- (const INTEGER &x, const int y)
INTEGER operator- (const int x, const INTEGER &y)
INTEGER & operator-= (INTEGER &x, const INTEGER &y)
INTEGER & operator-= (INTEGER &x, int n)
INTEGER operator- (const INTEGER &x)
INTEGER operator* (const INTEGER &x, const INTEGER &y)
INTEGER operator* (const INTEGER &x, const int y)
INTEGER operator* (const int x, const INTEGER &y)
INTEGER & operator*= (INTEGER &x, const INTEGER &y)
INTEGER & operator*= (INTEGER &x, int n)
INTEGER operator/ (const INTEGER &x, const INTEGER &y)
INTEGER operator/ (const INTEGER &x, const int n)
INTEGER operator/ (const int x, const INTEGER &y)
INTEGER & operator/= (INTEGER &x, const INTEGER &y)
INTEGER & operator/= (INTEGER &x, int n)
INTEGER operator% (const INTEGER &x, const INTEGER &y)
INTEGER & operator%= (INTEGER &x, const INTEGER &y)
INTEGER sqrt (const INTEGER &x)
INTEGER abs (const INTEGER &x)
bool operator< (const INTEGER &x, const INTEGER &y)
bool operator< (const INTEGER &x, const int y)
bool operator< (const int x, const INTEGER &y)
bool operator<= (const INTEGER &x, const INTEGER &y)
bool operator<= (const INTEGER &x, const int y)
bool operator<= (const int x, const INTEGER &y)
bool operator> (const INTEGER &x, const INTEGER &y)
bool operator> (const INTEGER &x, const int y)
bool operator> (const int x, const INTEGER &y)
bool operator>= (const INTEGER &x, const INTEGER &y)
bool operator>= (const INTEGER &x, const int y)
bool operator>= (const int x, const INTEGER &y)
bool operator== (const INTEGER &x, const INTEGER &y)
bool operator== (const INTEGER &x, const int i)
bool operator== (const int x, const INTEGER &y)
bool operator!= (const INTEGER &x, const INTEGER &y)
bool operator!= (const INTEGER &x, const int y)
bool operator!= (const int x, const INTEGER &y)
std::string swrite (const INTEGER &x, const int w)
std::string swrite (const INTEGER &x)
template<typename F , typename... Args>
auto exec (F f, const Args &...args) -> decltype(f(args...))
void limit_debug (const char *c)
void limit_debug2 (const char *c)
template<typename C , typename... ContArgs>
int geterror_exp (const C &, const ContArgs &...)
template<typename S >
int geterror_exp (const S &x)
template<typename S , typename T , typename... ContArgs>
std::enable_if< is_continuous< S >::value &&any_continuous< T, ContArgs... >::value, int >::type geterror_exp (const S &x, const T &y, const ContArgs &...z)
template<typename S , typename T , typename... ContArgs>
std::enable_if< is_continuous< S >::value &&!any_continuous< T, ContArgs... >::value, int >::type geterror_exp (const S &x, const T &, const ContArgs &...)
template<typename S , typename T , typename... ContArgs>
std::enable_if<!is_continuous< S >::value, int >::type geterror_exp (const S &, const T &y, const ContArgs &...z)
template<typename F , typename... ContArgs>
auto limit (F f, const ContArgs &...cont_args) -> typename std::enable_if< any_continuous< ContArgs... >::value, decltype(f(0, cont_args...))>::type
Continuous variant of the limit operator.
template<typename F , typename... DiscArgs>
auto limit (F f, const DiscArgs &...disc_args) -> typename std::enable_if<!any_continuous< DiscArgs... >::value, decltype(f(0, disc_args...))>::type
template<class ARGUMENT , class RESULT >
RESULT limit_mv (RESULT(*f)(int prec, int *choice, const ARGUMENT &), const ARGUMENT &x)
template<class ARGUMENT , class DISCRETE , class RESULT >
RESULT limit_lip (RESULT(*f)(int, const ARGUMENT &, DISCRETE param), int lip_value, bool(*on_domain)(const ARGUMENT &), const ARGUMENT &x, DISCRETE param)
template<class CONT_ARGUMENT , class DISCRETE_ARGUMENT , class RESULT , class PARAM >
RESULT lipschitz_1p_1a (RESULT(*f)(const DISCRETE_ARGUMENT &, const PARAM &param), int lip, bool(*on_domain)(const CONT_ARGUMENT &, const PARAM &param), const CONT_ARGUMENT &x, const PARAM &param)
REAL limit (FUNCTION< REAL, int > f)
template REAL limit (REAL(*f)(int, const REAL &), const REAL &)
template COMPLEX limit (COMPLEX(*)(int, COMPLEX const &), const COMPLEX &)
REAL round2 (const REAL &x)
int round (const REAL &x)
REAL acotan (const REAL &x)
void swap (REAL &a, REAL &b) noexcept
REAL operator<< (const REAL &x, int n)
REAL operator>> (const REAL &x, int n)
REAL operator+ (const REAL &x, const REAL &y)
template<>
REAL operator+ (const REAL &x, const int &i)
REAL operator- (const REAL &x, const REAL &y)
template<>
REAL operator- (const REAL &x, const int &n)
template<>
REAL operator- (const int &n, const REAL &x)
REAL operator* (const REAL &x, const REAL &y)
template<>
REAL operator* (const REAL &x, const int &n)
REAL operator/ (const REAL &x, const REAL &y)
template<>
REAL operator/ (const REAL &x, const int &n)
REAL square (const REAL &x)
LAZY_BOOLEAN operator< (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator<= (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator> (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator>= (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator== (const REAL &x, const REAL &y)
LAZY_BOOLEAN operator!= (const REAL &x, const REAL &y)
REAL abs (const REAL &x)
REALMATRIX limit_lip (REALMATRIX f(int, const REALMATRIX &), int lip, bool on_domain(const REALMATRIX &), const REALMATRIX &x)
unsigned int scale (const unsigned int w, const int p)
void sizetype_normalize (sizetype &e)
Try to keep the mantissa between max_mantissa and min_mantissa.
sizetype sizetype_normalize (sizetype &&e)
Try to keep the mantissa between max_mantissa and min_mantissa.
sizetype sizetype_power2 (typename sizetype::exponent_t exp)
void sizetype_inc (sizetype &x, const sizetype &y)
Increments x by y and normalizes x.
sizetype & operator+= (sizetype &x, const sizetype &y)
Increments x by y and normalizes x.
void sizetype_add_one (sizetype &x, const sizetype &y, typename sizetype::exponent_t zexp)
Sets x to y + 1*2^zexp and normalizes x.
void sizetype_inc_one (sizetype &x, typename sizetype::exponent_t zexp)
Sets x to x + 1*2^zexp and normalizes x.
void sizetype_inc2 (sizetype &x, const sizetype &y, const sizetype &z)
Increments x by y + z and normalizes x.
void sizetype_add_wo_norm (sizetype &x, const sizetype &y, const sizetype &z)
Adds y and z yielding x; no normalization.
void sizetype_add (sizetype &x, const sizetype &y, const sizetype &z)
Adds y and z yielding x and normalizes x.
sizetype sizetype_add_power2 (sizetype x, typename sizetype::exponent_t exp)
Computes x+2^exp and returns the normalized result.
sizetype operator+ (const sizetype &y, const sizetype &z)
Adds y and z yielding x and normalizes the result.
void sizetype_shift (sizetype &x, const sizetype &y, int s)
Shift y by s yielding x.
sizetype operator<< (const sizetype &y, int s)
Returns y left-shifted by s, normalized.
void sizetype_mult (sizetype &x, const sizetype &y, const sizetype &z)
Multiplies y and z yielding x and normalizes x.
sizetype operator* (const sizetype &y, const sizetype &z)
Sets y to y * z, normalized.
void sizetype_max (sizetype &x, const sizetype &y, const sizetype &z)
Computes the maximum of y and z and stores it in x.
sizetype max (const sizetype &y, const sizetype &z)
Returns the maximum of y and z.
void sizetype_set (sizetype &x, typename sizetype::mantissa_t mantissa, typename sizetype::exponent_t exponent)
Construct a sizetype value x from mantissa and exponent.
void sizetype_exact (sizetype &x)
constexpr sizetype sizetype_exact ()
bool sizetype_less (const sizetype &y, const sizetype &z)
Tests whether y<z. If y=z the result is allowed to be true OR false!
void sizetype_half (sizetype &x, const sizetype &y)
int sizetype_log2 (const sizetype &x)
Computes the integer approximation to the base-2 logarithm rounded towards positive infinity.
void sizetype_dec (sizetype &x, const sizetype &y)
void sizetype_dec (sizetype &x)
void sizetype_sqrt (sizetype &x, const sizetype &y)
void sizetype_div (sizetype &x, const sizetype &y, const sizetype &z)
_SetRwidth setRwidth (int __n)
_SetRflags setRflags (float_form n)
Variables
double ln2_time = 0.0
double pi_time = 0.0
const int iRRAM_prec_steps =512
const int *const iRRAM_prec_array = _iRRAM_prec_array
iRRAM_TLS state_t state
orstream cout
irstream cin
const int MANTISSA_BITS = (int)(CHAR_BIT * sizeof(sizetype::mantissa_t))
const int DIFF_BITS = 3
const int BIT_RANGE = 8
const int BIT_RANGE2 = 8
const int GUARD_BITS = MANTISSA_BITS - DIFF_BITS
const sizetype::mantissa_t max_mantissa = 1 << GUARD_BITS
const sizetype::exponent_t min_mantissa = 1 << (GUARD_BITS-BIT_RANGE)
const sizetype::exponent_t min_exponent = MP_min + MANTISSA_BITS
orstream cerr
orstream clog
Typedef Documentation
template<typename... T> using iRRAM::any_continuous = typedef disjunction<is_continuous<T>...>
Definition at line 67 of file helper-templates.hh.
template<typename... T> using iRRAM::conjunction = typedef negation<disjunction<negation<T>...>>
Definition at line 47 of file helper-templates.hh.
template<typename Base , typename EquivBase , typename Compat , typename Ret = Base> using iRRAM::enable_if_compat = typedef typename std::enable_if< std::is_same<typename std::remove_cv<EquivBase>::type, typename std::remove_cv<Base>::type >::value && std::is_convertible<Compat,Base>::value ,Ret>::type
Definition at line 18 of file helper-templates.hh.
typedef generic_sizetype<unsigned int,int> iRRAM::sizetype
Definition at line 73 of file core.h.
Enumeration Type Documentation
enum iRRAM::float_form : int strong
Enumerator
absolute
relative
show
Definition at line 176 of file core.h.
Function Documentation
REAL iRRAM::abs (const COMPLEX & z)
Definition at line 98 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag, iRRAM::COMPLEX::_real, iRRAM::COMPLEX::abs, bound(), iRRAM::COMPLEX::COMPLEX(), iRRAM::COMPLEX::imag, iRRAM::COMPLEX::real, and sqrt().
Referenced by atan(), colsumnorm(), fabs(), mag(), maxnorm(), power(), rowsumnorm(), and square().
REAL iRRAM::abs (const REAL & x) inline
Definition at line 817 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
INTERVAL iRRAM::acos (const INTERVAL & x)
Definition at line 301 of file INTERVAL.cc.
References iRRAM::INTERVAL::acos, iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
DYADIC iRRAM::ADD (const DYADIC & x, const DYADIC & y, const int p)
Definition at line 66 of file DYADIC.cc.
References MP_add, MP_init, MP_type, and iRRAM::DYADIC::value.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::addition (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > & a) inline
Definition at line 276 of file FUNCTION.h.
References from_algorithm().
Referenced by operator+().
DYADIC iRRAM::approx (const REAL & x, const int p)
Computes a dyadic approximation to x that is accurate to 2^p.
This is a multi-valued function.
Reiteration is used to ensure \(x_\varepsilon\leq2^{p+1}\). The computed value at least as precise as \(x_c\) rounded to a multiple of \(2^{p-1}\).
Parameters
x the real number to approximate
p accuracy
Returns
a dyadic approximation q that satisfies |x-q|<2^p.
Exceptions
Iteration when \(2^{p+1}<x_\varepsilon\)
See also
REITERATE
Definition at line 605 of file REALS.cc.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::approx, iRRAM::iRRAM_thread_data_class::cache_mp, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, MP_copy, MP_duplicate_w_init, MP_init, MP_type, iRRAM::iRRAM_cache< DATA >::put(), iRRAM::REAL::REAL(), REITERATE, sizetype_less(), sizetype_power2(), state, iRRAM::state_t::thread_data_address, and iRRAM::REAL::value.
Referenced by mpfr_ext_cos(), mpfr_ext_exp(), mpfr_ext_log(), mpfr_ext_sin(), mpfr_ext_test(), mpfr_wrapper(), and root().
REAL iRRAM::arg (const COMPLEX & z)
Definition at line 165 of file COMPLEX.cc.
References iRRAM::COMPLEX::abs, acos(), asin(), choose(), iRRAM::COMPLEX::COMPLEX(), iRRAM::COMPLEX::imag, pi(), positive(), and iRRAM::COMPLEX::real.
Referenced by mpfr_wrapper().
INTERVAL iRRAM::asin (const INTERVAL & x)
Definition at line 296 of file INTERVAL.cc.
References iRRAM::INTERVAL::asin, iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
INTERVAL iRRAM::atan (const INTERVAL & x)
Definition at line 306 of file INTERVAL.cc.
References iRRAM::INTERVAL::atan, iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
REAL iRRAM::atoREAL (const char * s)
Definition at line 1019 of file REALS.cc.
References strtoREAL().
Referenced by iRRAM::REAL::seterror().
int iRRAM::bound (const REALMATRIX & x, const int k)
Definition at line 237 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::bound, ELEMENT, iRRAM::REALMATRIX::maxcolumn, and iRRAM::REALMATRIX::maxrow.
Referenced by abs(), csqrt(), euler(), exp(), ln2(), root(), and tan().
LAZY_BOOLEAN iRRAM::bound (const REAL & x, const int k)
Definition at line 726 of file REALS.cc.
References iRRAM::REAL::bound, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, sizetype_add(), sizetype_add_one(), sizetype_less(), sizetype_set(), iRRAM::REAL::value, and iRRAM::REAL::vsize.
int iRRAM::check (const LAZY_BOOLEAN & lb)
Definition at line 49 of file LAZY_BOOLEAN.cc.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::iRRAM_thread_data_class::cache_i, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM::iRRAM_cache< DATA >::put(), state, and iRRAM::state_t::thread_data_address.
int iRRAM::choose (const LAZY_BOOLEAN & x1, const LAZY_BOOLEAN & x2, const LAZY_BOOLEAN & x3, const LAZY_BOOLEAN & x4, const LAZY_BOOLEAN & x5, const LAZY_BOOLEAN & x6)
Definition at line 58 of file LAZY_BOOLEAN.cc.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::iRRAM_thread_data_class::cache_i, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG1, iRRAM::iRRAM_cache< DATA >::put(), REITERATE, state, and iRRAM::state_t::thread_data_address.
Referenced by arg(), atan(), cos(), cosech(), cosh(), coth(), sech(), sin(), sinh(), and tanh().
REAL iRRAM::colsumnorm (const REALMATRIX & x)
Definition at line 289 of file REALMATRIX.cc.
References abs(), iRRAM::REALMATRIX::bound, iRRAM::REALMATRIX::columns, iRRAM::REALMATRIX::eye, iRRAM::REALMATRIX::maxcolumn, maximum(), iRRAM::REALMATRIX::maxrow, and iRRAM::REALMATRIX::rows.
REAL iRRAM::colsumnorm (const SPARSEREALMATRIX & x)
Definition at line 575 of file SPARSEREALMATRIX.cc.
References abs(), iRRAM::SPARSEREALMATRIX::colvector, iRRAM::SPARSEREALMATRIX::maxcolumn, maximum(), iRRAM::SPM_ELEMENT::nextrow, and iRRAM::SPM_ELEMENT::value.
template<class RESULT , class INTERMEDIATE , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::compose (const FUNCTION< RESULT, INTERMEDIATE > & outer, const FUNCTION< INTERMEDIATE, PARAM... > & inner) inline
Definition at line 142 of file FUNCTION.h.
References from_algorithm().
Referenced by iRRAM::FUNCTION< RESULT, PARAM >::operator()().
INTERVAL iRRAM::cos (const INTERVAL & x)
Definition at line 221 of file INTERVAL.cc.
References choose(), iRRAM::INTERVAL::cos, iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), modulo(), pi(), and iRRAM::INTERVAL::upp.
INTEGER iRRAM::denominator (const RATIONAL & x)
Definition at line 246 of file RATIONAL.cc.
References MP_int_init, MP_int_type, and MP_rat_get_denominator.
LAZY_BOOLEAN iRRAM::disjoint (const INTERVAL & x, const INTERVAL & y)
Definition at line 329 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
DYADIC iRRAM::DIV (const DYADIC & x, const DYADIC & y, const int p)
Definition at line 87 of file DYADIC.cc.
References MP_div, MP_init, MP_type, and iRRAM::DYADIC::value.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::division (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > & a) inline
Definition at line 357 of file FUNCTION.h.
References from_algorithm().
Referenced by operator/().
REALMATRIX iRRAM::equilib (const SPARSEREALMATRIX & x)
Definition at line 419 of file REALMATRIX.cc.
References equilib_del().
Referenced by iRRAM::REALMATRIX::seterror().
void iRRAM::equilib_del (SPARSEREALMATRIX & chain, REALMATRIX & result)
Definition at line 426 of file REALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, cout, iRRAM::SPARSEREALMATRIX::filled, iRRAM::SPARSEREALMATRIX::hotspot, iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPM_ELEMENT::rowindex, iRRAM::SPARSEREALMATRIX::rowvector, sparse_get_ptr(), sparse_set(), iRRAM::SPM_ELEMENT::value, and iRRAM::REALMATRIX::zeroes.
Referenced by equilib(), and iRRAM::REALMATRIX::seterror().
template<typename F , typename... Args> auto iRRAM::exec (F f, const Args &... args) -> decltype(f(args...))
Definition at line 85 of file lib.h.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::state_t::cache_active, cerr, iRRAM::iRRAM_cache_type::clear(), cout, iRRAM::state_t::debug, iRRAM::state_t::highlevel, iRRAM::cachelist::id, iRRAM::stiff::inc_step(), iRRAM::state_t::infinite, iRRAM::ITERATION_DATA::inlimit, iRRAM::state_t::inReiterate, iRRAM_error_msg, iRRAM_likely, iRRAM_unlikely, iRRAM_VERSION_rt, iRRAM::state_t::max_active, iRRAM::state_t::max_prec, iRRAM::Iteration::prec_diff, iRRAM::ITERATION_DATA::prec_policy, iRRAM::state_t::prec_skip, iRRAM::state_t::prec_start, iRRAM::ITERATION_DATA::prec_step, iRRAM::orstream::reset(), iRRAM::iRRAM_cache_type::rewind(), iRRAM::orstream::rewind(), show_statistics(), state, iRRAM::state_t::thread_data_address, and iRRAM::iRRAM_Numerical_Exception::type.
Referenced by iRRAM_exec(), main(), and mpfr_wrapper().
INTERVAL iRRAM::exp (const INTERVAL & x)
Definition at line 148 of file INTERVAL.cc.
References iRRAM::INTERVAL::exp, iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
REALMATRIX iRRAM::eye (unsigned int rows)
Definition at line 48 of file REALMATRIX.cc.
References ELEMENT, and iRRAM::REALMATRIX::rows.
INTERVAL iRRAM::fabs (const INTERVAL & x)
Definition at line 126 of file INTERVAL.cc.
References abs(), iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
template<class RESULT1 , class RESULT2 , class... PARAM> FUNCTION<RESULT1,PARAM... > iRRAM::first (const FUNCTION< std::pair< RESULT1, RESULT2 >, PARAM... > & f) inline
Definition at line 190 of file FUNCTION.h.
References from_algorithm().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::from_algorithm (RESULT(evalp)(const PARAM &...z)) inline
Definition at line 122 of file FUNCTION.h.
Referenced by addition(), iRRAM::FUNCTION< RESULT, PARAM >::bind(), compose(), division(), first(), juxtaposition(), LAZY_BOOLEAN_FUNCTION_and(), LAZY_BOOLEAN_FUNCTION_not(), LAZY_BOOLEAN_FUNCTION_or(), less_than(), multiplication(), polynomial(), product(), projection(), second(), and subtraction().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::from_algorithm (const std::function< RESULT(const PARAM &...)> & evalp) inline
Definition at line 129 of file FUNCTION.h.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::from_value (const RESULT & value) inline
Definition at line 136 of file FUNCTION.h.
template<typename C , typename... ContArgs> int iRRAM::geterror_exp (const C & , const ContArgs & ...)
Referenced by geterror_exp(), limit(), and limit_debug2().
template<typename S > int iRRAM::geterror_exp (const S & x)
Definition at line 173 of file limit_templates.h.
template<typename S , typename T , typename... ContArgs> std::enable_if<is_continuous<S>::value && any_continuous<T,ContArgs...>::value,int>::type iRRAM::geterror_exp (const S & x, const T & y, const ContArgs &... z)
Definition at line 181 of file limit_templates.h.
References geterror_exp(), and max().
template<typename S , typename T , typename... ContArgs> std::enable_if<is_continuous<S>::value && !any_continuous<T,ContArgs...>::value,int>::type iRRAM::geterror_exp (const S & x, const T & , const ContArgs & ...)
Definition at line 189 of file limit_templates.h.
References geterror_exp().
template<typename S , typename T , typename... ContArgs> std::enable_if<!is_continuous<S>::value,int>::type iRRAM::geterror_exp (const S & , const T & y, const ContArgs &... z)
Definition at line 196 of file limit_templates.h.
References geterror_exp().
REAL iRRAM::imag (const COMPLEX & z)
Definition at line 95 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag.
LAZY_BOOLEAN iRRAM::in (const REAL & x, const INTERVAL & y)
Definition at line 332 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
LAZY_BOOLEAN iRRAM::in_interior (const INTERVAL & x, const INTERVAL & y)
Definition at line 326 of file INTERVAL.cc.
References iRRAM::INTERVAL::superset.
REAL iRRAM::inf (const INTERVAL & x)
Definition at line 106 of file INTERVAL.cc.
References iRRAM::INTERVAL::low.
INTERVAL iRRAM::intersect (const INTERVAL & x, const INTERVAL & y)
Definition at line 338 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
INTERVAL iRRAM::interval_hull (const INTERVAL & x, const INTERVAL & y)
Definition at line 335 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
template<class RESULT1 , class RESULT2 , class... PARAM> FUNCTION<std::pair<RESULT1,RESULT2>,PARAM... > iRRAM::juxtaposition (const FUNCTION< RESULT1, PARAM... > & f_1, const FUNCTION< RESULT2, PARAM... > & f_2) inline
Definition at line 175 of file FUNCTION.h.
References from_algorithm().
Referenced by operator&&(), operator*(), operator+(), operator-(), operator/(), operator<(), operator>(), and operator||().
template<class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::LAZY_BOOLEAN_FUNCTION_and (const FUNCTION< std::pair< LAZY_BOOLEAN, LAZY_BOOLEAN >, PARAM... > & a) inline
Definition at line 538 of file FUNCTION.h.
References from_algorithm().
Referenced by operator&&().
template<class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::LAZY_BOOLEAN_FUNCTION_not (const FUNCTION< LAZY_BOOLEAN, PARAM... > & a) inline
Definition at line 586 of file FUNCTION.h.
References from_algorithm().
Referenced by operator!().
template<class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::LAZY_BOOLEAN_FUNCTION_or (const FUNCTION< std::pair< LAZY_BOOLEAN, LAZY_BOOLEAN >, PARAM... > & a) inline
Definition at line 562 of file FUNCTION.h.
References from_algorithm().
Referenced by operator||().
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::less_than (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > & a) inline
Definition at line 467 of file FUNCTION.h.
References from_algorithm().
Referenced by operator<(), and operator>().
template REAL iRRAM::limit (REAL(*)(int, REAL const &) , REAL const &)
template COMPLEX iRRAM::limit (COMPLEX(*)(int, const COMPLEX &) , COMPLEX const &)
REALMATRIX iRRAM::limit_lip (REALMATRIX fint, const REALMATRIX &, int lip, bool on_domainconst REALMATRIX &, const REALMATRIX & x)
template COMPLEX iRRAM::limit_mv< COMPLEX, COMPLEX > (COMPLEX(*)(int, int *, COMPLEX const &) , COMPLEX const &)
Referenced by limit().
template REALMATRIX iRRAM::limit_mv< REALMATRIX, REALMATRIX > (REALMATRIX(*)(int, int *, REALMATRIX const &) , REALMATRIX const &)
Referenced by limit().
INTERVAL iRRAM::log (const INTERVAL & x)
Definition at line 153 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::log, iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
REAL iRRAM::mag (const INTERVAL & x)
Definition at line 118 of file INTERVAL.cc.
References abs(), iRRAM::INTERVAL::low, maximum(), and iRRAM::INTERVAL::upp.
REAL iRRAM::maxnorm (const REALMATRIX & x)
Definition at line 271 of file REALMATRIX.cc.
References abs(), iRRAM::REALMATRIX::maxcolumn, maximum(), iRRAM::REALMATRIX::maxrow, size(), and iRRAM::REALMATRIX::values.
REAL iRRAM::maxnorm (const SPARSEREALMATRIX & x)
Definition at line 545 of file SPARSEREALMATRIX.cc.
References abs(), maximum(), iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPARSEREALMATRIX::rowvector, and iRRAM::SPM_ELEMENT::value.
REAL iRRAM::mid (const INTERVAL & x)
Definition at line 114 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
REAL iRRAM::mig (const INTERVAL & x)
Definition at line 122 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
int iRRAM::module (REAL(*)(const REAL &) f, const REAL & x, int p) related
Definition at line 1121 of file REALS.cc.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::REAL::adderror(), iRRAM::REAL::approx, iRRAM::iRRAM_thread_data_class::cache_i, iRRAM::state_t::debug, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::REAL::geterror(), iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG2, iRRAM_unlikely, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::iRRAM_cache< DATA >::put(), iRRAM::REAL::seterror(), sizetype_power2(), state, and iRRAM::state_t::thread_data_address.
DYADIC iRRAM::MULT (const DYADIC & x, const DYADIC & y, const int p)
Definition at line 80 of file DYADIC.cc.
References MP_init, MP_mul, MP_type, and iRRAM::DYADIC::value.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::multiplication (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > & a) inline
Definition at line 330 of file FUNCTION.h.
References from_algorithm().
Referenced by operator*().
INTEGER iRRAM::numerator (const RATIONAL & x)
Definition at line 253 of file RATIONAL.cc.
References MP_int_init, MP_int_type, and MP_rat_get_numerator.
REALMATRIX iRRAM::ones (unsigned int rows, unsigned int columns)
Definition at line 64 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::columns, ELEMENT, and iRRAM::REALMATRIX::rows.
LAZY_BOOLEAN iRRAM::operator! (const LAZY_BOOLEAN & x) noexcept
Definition at line 108 of file LAZY_BOOLEAN.cc.
bool iRRAM::operator! (orstream & x)
Definition at line 335 of file STREAMS.cc.
References iRRAM::iRRAM_thread_data_class::cache_b, iRRAM_inexec, state, iRRAM::orstream::target, and iRRAM::state_t::thread_data_address.
bool iRRAM::operator! (irstream & x)
Definition at line 377 of file STREAMS.cc.
References iRRAM::iRRAM_thread_data_class::cache_b, iRRAM_inexec, state, and iRRAM::state_t::thread_data_address.
template<class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator! (const FUNCTION< LAZY_BOOLEAN, PARAM... > & a) inline
Definition at line 601 of file FUNCTION.h.
References LAZY_BOOLEAN_FUNCTION_not(), and limit().
bool iRRAM::operator!= (const DYADIC & x, const DYADIC & y)
Definition at line 120 of file DYADIC.cc.
bool iRRAM::operator!= (const INTEGER & x, const INTEGER & y) inline
Definition at line 494 of file INTEGER.h.
bool iRRAM::operator!= (const INTEGER & x, const int y) inline
Definition at line 495 of file INTEGER.h.
bool iRRAM::operator!= (const int x, const INTEGER & y) inline
Definition at line 496 of file INTEGER.h.
LAZY_BOOLEAN iRRAM::operator!= (const REAL & x, const REAL & y) inline
Definition at line 815 of file REAL.h.
INTEGER iRRAM::operator% (const INTEGER & x, const INTEGER & y) inline
Definition at line 416 of file INTEGER.h.
References MP_int_init, MP_int_modulo, and MP_int_type.
INTEGER& iRRAM::operator%= (INTEGER & x, const INTEGER & y) inline
Definition at line 423 of file INTEGER.h.
References MP_int_modulo.
LAZY_BOOLEAN iRRAM::operator&& (const LAZY_BOOLEAN & x, const LAZY_BOOLEAN & y) noexcept
Definition at line 92 of file LAZY_BOOLEAN.cc.
template<class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator&& (const FUNCTION< LAZY_BOOLEAN, PARAM... > & a, const FUNCTION< LAZY_BOOLEAN, PARAM... > & b) inline
Definition at line 553 of file FUNCTION.h.
References juxtaposition(), and LAZY_BOOLEAN_FUNCTION_and().
INTERVAL iRRAM::operator* (const INTERVAL & x, const INTERVAL & y)
Definition at line 63 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
COMPLEX iRRAM::operator* (const COMPLEX & x, const COMPLEX & y)
Definition at line 74 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag, iRRAM::COMPLEX::_real, and iRRAM::COMPLEX::COMPLEX().
REALMATRIX iRRAM::operator* (const REALMATRIX & x, const REALMATRIX & y)
Definition at line 110 of file REALMATRIX.cc.
References ELEMENT, iRRAM::REALMATRIX::maxcolumn, and iRRAM::REALMATRIX::maxrow.
REALMATRIX iRRAM::operator* (const REALMATRIX & x, const REAL & y)
Definition at line 219 of file REALMATRIX.cc.
References ELEMENT, iRRAM::REALMATRIX::maxcolumn, and iRRAM::REALMATRIX::maxrow.
INTEGER iRRAM::operator* (const INTEGER & x, const INTEGER & y) inline
Definition at line 333 of file INTEGER.h.
References MP_int_init, MP_int_mul, and MP_int_type.
INTEGER iRRAM::operator* (const INTEGER & x, const int y) inline
Definition at line 340 of file INTEGER.h.
References MP_int_init, MP_int_mul_si, and MP_int_type.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator* (const FUNCTION< RESULT, PARAM... > & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 345 of file FUNCTION.h.
References juxtaposition(), and multiplication().
INTEGER iRRAM::operator* (const int x, const INTEGER & y) inline
Definition at line 347 of file INTEGER.h.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator* (const FUNCTION< RESULT, PARAM... > & a, const RESULT & b) inline
Definition at line 404 of file FUNCTION.h.
References juxtaposition(), and multiplication().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator* (const RESULT & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 412 of file FUNCTION.h.
References juxtaposition(), and multiplication().
SPARSEREALMATRIX iRRAM::operator* (const SPARSEREALMATRIX & x, const SPARSEREALMATRIX & y)
Definition at line 431 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::maxcolumn, iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::rowindex, iRRAM::SPARSEREALMATRIX::rowvector, iRRAM::SPARSEREALMATRIX::sparse_set, and iRRAM::SPM_ELEMENT::value.
REAL iRRAM::operator* (const REAL & x, const REAL & y) inline
Definition at line 663 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
template<> REAL iRRAM::operator* (const REAL & x, const int & n) inline
Definition at line 690 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
RATIONAL& iRRAM::operator*= (RATIONAL & x, const RATIONAL & y)
Definition at line 202 of file RATIONAL.cc.
References MP_rat_mul.
RATIONAL& iRRAM::operator*= (RATIONAL & x, const int n)
Definition at line 207 of file RATIONAL.cc.
References MP_rat_mul_si.
INTEGER& iRRAM::operator*= (INTEGER & x, const INTEGER & y) inline
Definition at line 356 of file INTEGER.h.
References MP_int_mul.
INTEGER& iRRAM::operator*= (INTEGER & x, int n) inline
Definition at line 361 of file INTEGER.h.
References MP_int_mul_si.
COMPLEX iRRAM::operator+ (const COMPLEX & x, const COMPLEX & y)
Definition at line 56 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag, iRRAM::COMPLEX::_real, and iRRAM::COMPLEX::COMPLEX().
REALMATRIX iRRAM::operator+ (const REALMATRIX & x, const REALMATRIX & y)
Definition at line 86 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::maxcolumn, iRRAM::REALMATRIX::maxrow, size(), and iRRAM::REALMATRIX::values.
INTEGER iRRAM::operator+ (const INTEGER & x, const INTEGER & y) inline
Definition at line 254 of file INTEGER.h.
References MP_int_add, MP_int_init, and MP_int_type.
INTEGER iRRAM::operator+ (const INTEGER & x, const int y) inline
Definition at line 261 of file INTEGER.h.
References MP_int_add_ui, MP_int_init, MP_int_sub_ui, and MP_int_type.
INTEGER iRRAM::operator+ (const int x, const INTEGER & y) inline
Definition at line 269 of file INTEGER.h.
SPARSEREALMATRIX iRRAM::operator+ (const SPARSEREALMATRIX & x, const SPARSEREALMATRIX & y)
Definition at line 284 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::maxcolumn, iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPARSEREALMATRIX::rowvector, iRRAM::SPARSEREALMATRIX::sparse_set, and iRRAM::SPM_ELEMENT::value.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator+ (const FUNCTION< RESULT, PARAM... > & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 291 of file FUNCTION.h.
References addition(), and juxtaposition().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator+ (const FUNCTION< RESULT, PARAM... > & a, const RESULT & b) inline
Definition at line 384 of file FUNCTION.h.
References addition(), and juxtaposition().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator+ (const RESULT & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 392 of file FUNCTION.h.
References addition(), and juxtaposition().
REAL iRRAM::operator+ (const REAL & x, const REAL & y) inline
Definition at line 587 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
template<> REAL iRRAM::operator+ (const REAL & x, const int & i) inline
Definition at line 600 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
INTERVAL& iRRAM::operator+= (INTERVAL & x, const INTERVAL & y)
Definition at line 35 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
RATIONAL& iRRAM::operator+= (RATIONAL & x, const RATIONAL & y)
Definition at line 160 of file RATIONAL.cc.
References MP_rat_add.
RATIONAL& iRRAM::operator+= (RATIONAL & x, int y)
Definition at line 166 of file RATIONAL.cc.
References MP_rat_add_si.
INTEGER& iRRAM::operator+= (INTEGER & x, const INTEGER & y) inline
Definition at line 275 of file INTEGER.h.
References MP_int_add.
INTEGER& iRRAM::operator+= (INTEGER & x, int n) inline
Definition at line 280 of file INTEGER.h.
References MP_int_add_ui, and MP_int_sub_ui.
INTERVAL iRRAM::operator- (const INTERVAL & x)
Definition at line 49 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), and iRRAM::INTERVAL::upp.
COMPLEX iRRAM::operator- (const COMPLEX & x, const COMPLEX & y)
Definition at line 62 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag, iRRAM::COMPLEX::_real, and iRRAM::COMPLEX::COMPLEX().
COMPLEX iRRAM::operator- (const COMPLEX & x)
Definition at line 68 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag, iRRAM::COMPLEX::_real, and iRRAM::COMPLEX::COMPLEX().
REALMATRIX iRRAM::operator- (const REALMATRIX & x, const REALMATRIX & y)
Definition at line 98 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::maxcolumn, iRRAM::REALMATRIX::maxrow, size(), and iRRAM::REALMATRIX::values.
RATIONAL iRRAM::operator- (int x, RATIONAL y)
Definition at line 176 of file RATIONAL.cc.
References MP_rat_neg.
RATIONAL iRRAM::operator- (RATIONAL x)
Definition at line 192 of file RATIONAL.cc.
References MP_rat_neg.
INTEGER iRRAM::operator- (const INTEGER & x, const INTEGER & y) inline
Definition at line 291 of file INTEGER.h.
References MP_int_init, MP_int_sub, and MP_int_type.
INTEGER iRRAM::operator- (const INTEGER & x, const int y) inline
Definition at line 298 of file INTEGER.h.
INTEGER iRRAM::operator- (const int x, const INTEGER & y) inline
Definition at line 303 of file INTEGER.h.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator- (const FUNCTION< RESULT, PARAM... > & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 318 of file FUNCTION.h.
References juxtaposition(), and subtraction().
SPARSEREALMATRIX iRRAM::operator- (const SPARSEREALMATRIX & x, const SPARSEREALMATRIX & y)
Definition at line 320 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::maxcolumn, iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPARSEREALMATRIX::rowvector, iRRAM::SPARSEREALMATRIX::sparse_set, and iRRAM::SPM_ELEMENT::value.
INTEGER iRRAM::operator- (const INTEGER & x) inline
Definition at line 322 of file INTEGER.h.
References MP_int_init, MP_int_neg, and MP_int_type.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator- (const FUNCTION< RESULT, PARAM... > & a, const RESULT & b) inline
Definition at line 424 of file FUNCTION.h.
References juxtaposition(), and subtraction().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator- (const RESULT & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 432 of file FUNCTION.h.
References juxtaposition(), and subtraction().
REAL iRRAM::operator- (const REAL & x, const REAL & y) inline
Definition at line 623 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
template<> REAL iRRAM::operator- (const REAL & x, const int & n) inline
Definition at line 632 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
template<> REAL iRRAM::operator- (const int & n, const REAL & x) inline
Definition at line 641 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
INTERVAL& iRRAM::operator-= (INTERVAL & x, const INTERVAL & y)
Definition at line 42 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
RATIONAL& iRRAM::operator-= (RATIONAL & x, const RATIONAL & y)
Definition at line 183 of file RATIONAL.cc.
References MP_rat_sub.
INTEGER& iRRAM::operator-= (INTEGER & x, const INTEGER & y) inline
Definition at line 311 of file INTEGER.h.
References MP_int_sub.
INTEGER& iRRAM::operator-= (INTEGER & x, int n) inline
Definition at line 316 of file INTEGER.h.
COMPLEX iRRAM::operator/ (const COMPLEX & x, const COMPLEX & y)
Definition at line 82 of file COMPLEX.cc.
References iRRAM::COMPLEX::_imag, iRRAM::COMPLEX::_real, and iRRAM::COMPLEX::COMPLEX().
INTERVAL iRRAM::operator/ (const INTERVAL & x, const INTERVAL & y)
Definition at line 94 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
REALMATRIX iRRAM::operator/ (const REALMATRIX & x, const REALMATRIX & y)
Definition at line 126 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::solve.
RATIONAL iRRAM::operator/ (int x, RATIONAL y)
Definition at line 217 of file RATIONAL.cc.
References MP_rat_si_div.
REALMATRIX iRRAM::operator/ (const REALMATRIX & x, const REAL & y)
Definition at line 228 of file REALMATRIX.cc.
References ELEMENT, iRRAM::REALMATRIX::maxcolumn, and iRRAM::REALMATRIX::maxrow.
INTEGER iRRAM::operator/ (const INTEGER & x, const INTEGER & y) inline
Definition at line 371 of file INTEGER.h.
References MP_int_div, MP_int_init, and MP_int_type.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator/ (const FUNCTION< RESULT, PARAM... > & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 372 of file FUNCTION.h.
References division(), and juxtaposition().
INTEGER iRRAM::operator/ (const INTEGER & x, const int n) inline
Definition at line 379 of file INTEGER.h.
References MP_int_div_ui, MP_int_init, MP_int_neg, and MP_int_type.
INTEGER iRRAM::operator/ (const int x, const INTEGER & y) inline
Definition at line 391 of file INTEGER.h.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator/ (const FUNCTION< RESULT, PARAM... > & a, const RESULT & b) inline
Definition at line 444 of file FUNCTION.h.
References division(), and juxtaposition().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::operator/ (const RESULT & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 452 of file FUNCTION.h.
References division(), and juxtaposition().
SPARSEREALMATRIX iRRAM::operator/ (const SPARSEREALMATRIX & x, const SPARSEREALMATRIX & y)
Definition at line 455 of file SPARSEREALMATRIX.cc.
References iRRAM::SPARSEREALMATRIX::solve.
REAL iRRAM::operator/ (const REAL & x, const REAL & y) inline
Definition at line 720 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
template<> REAL iRRAM::operator/ (const REAL & x, const int & n) inline
Definition at line 754 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
RATIONAL& iRRAM::operator/= (RATIONAL & x, const RATIONAL & y)
Definition at line 223 of file RATIONAL.cc.
References MP_rat_div.
RATIONAL& iRRAM::operator/= (RATIONAL & x, const int n)
Definition at line 228 of file RATIONAL.cc.
References MP_rat_div_si.
INTEGER& iRRAM::operator/= (INTEGER & x, const INTEGER & y) inline
Definition at line 397 of file INTEGER.h.
References MP_int_div.
INTEGER& iRRAM::operator/= (INTEGER & x, int n) inline
Definition at line 402 of file INTEGER.h.
References MP_int_div_ui, and MP_int_neg.
bool iRRAM::operator< (const DYADIC & x, const DYADIC & y)
Definition at line 109 of file DYADIC.cc.
References MP_compare, and iRRAM::DYADIC::value.
bool iRRAM::operator< (const RATIONAL & x, const RATIONAL & y)
Definition at line 265 of file RATIONAL.cc.
References MP_rat_compare.
bool iRRAM::operator< (const INTEGER & x, const INTEGER & y) inline
Definition at line 467 of file INTEGER.h.
References MP_int_compare.
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator< (const FUNCTION< RESULT, PARAM... > & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 483 of file FUNCTION.h.
References juxtaposition(), and less_than().
bool iRRAM::operator< (const INTEGER & x, const int y) inline
Definition at line 470 of file INTEGER.h.
bool iRRAM::operator< (const int x, const INTEGER & y) inline
Definition at line 471 of file INTEGER.h.
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator< (const RESULT & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 511 of file FUNCTION.h.
References juxtaposition(), and less_than().
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator< (const FUNCTION< RESULT, PARAM... > & a, const RESULT & b) inline
Definition at line 503 of file FUNCTION.h.
References juxtaposition(), and less_than().
LAZY_BOOLEAN iRRAM::operator< (const REAL & x, const REAL & y) inline
Definition at line 800 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, and iRRAM::REAL::value.
INTEGER iRRAM::operator<< (const INTEGER & x, const int n) inline
Definition at line 234 of file INTEGER.h.
References iRRAM::INTEGER::scale.
REAL iRRAM::operator<< (const REAL & x, int n) inline
Definition at line 584 of file REAL.h.
References iRRAM::REAL::scale.
bool iRRAM::operator<= (const DYADIC & x, const DYADIC & y)
Definition at line 114 of file DYADIC.cc.
bool iRRAM::operator<= (const INTEGER & x, const INTEGER & y) inline
Definition at line 473 of file INTEGER.h.
bool iRRAM::operator<= (const INTEGER & x, const int y) inline
Definition at line 474 of file INTEGER.h.
bool iRRAM::operator<= (const int x, const INTEGER & y) inline
Definition at line 475 of file INTEGER.h.
LAZY_BOOLEAN iRRAM::operator<= (const REAL & x, const REAL & y) inline
Definition at line 811 of file REAL.h.
bool iRRAM::operator== (const DYADIC & x, const DYADIC & y)
Definition at line 116 of file DYADIC.cc.
References MP_compare, and iRRAM::DYADIC::value.
bool iRRAM::operator== (const RATIONAL & x, const RATIONAL & y)
Definition at line 274 of file RATIONAL.cc.
References MP_rat_equal.
bool iRRAM::operator== (const INTEGER & x, const INTEGER & y) inline
Definition at line 487 of file INTEGER.h.
References MP_int_compare.
bool iRRAM::operator== (const INTEGER & x, const int i) inline
Definition at line 491 of file INTEGER.h.
bool iRRAM::operator== (const int x, const INTEGER & y) inline
Definition at line 492 of file INTEGER.h.
LAZY_BOOLEAN iRRAM::operator== (const REAL & x, const REAL & y) inline
Definition at line 814 of file REAL.h.
bool iRRAM::operator> (const DYADIC & x, const DYADIC & y)
Definition at line 113 of file DYADIC.cc.
bool iRRAM::operator> (const INTEGER & x, const INTEGER & y) inline
Definition at line 477 of file INTEGER.h.
bool iRRAM::operator> (const INTEGER & x, const int y) inline
Definition at line 478 of file INTEGER.h.
bool iRRAM::operator> (const int x, const INTEGER & y) inline
Definition at line 479 of file INTEGER.h.
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator> (const FUNCTION< RESULT, PARAM... > & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 491 of file FUNCTION.h.
References juxtaposition(), and less_than().
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator> (const FUNCTION< RESULT, PARAM... > & a, const RESULT & b) inline
Definition at line 519 of file FUNCTION.h.
References juxtaposition(), and less_than().
template<class RESULT , class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator> (const RESULT & a, const FUNCTION< RESULT, PARAM... > & b) inline
Definition at line 527 of file FUNCTION.h.
References juxtaposition(), and less_than().
LAZY_BOOLEAN iRRAM::operator> (const REAL & x, const REAL & y) inline
Definition at line 812 of file REAL.h.
bool iRRAM::operator>= (const DYADIC & x, const DYADIC & y)
Definition at line 115 of file DYADIC.cc.
bool iRRAM::operator>= (const INTEGER & x, const INTEGER & y) inline
Definition at line 481 of file INTEGER.h.
bool iRRAM::operator>= (const INTEGER & x, const int y) inline
Definition at line 482 of file INTEGER.h.
bool iRRAM::operator>= (const int x, const INTEGER & y) inline
Definition at line 483 of file INTEGER.h.
LAZY_BOOLEAN iRRAM::operator>= (const REAL & x, const REAL & y) inline
Definition at line 813 of file REAL.h.
INTEGER iRRAM::operator>> (const INTEGER & x, const int n) inline
Definition at line 243 of file INTEGER.h.
References iRRAM::INTEGER::scale.
REAL iRRAM::operator>> (const REAL & x, int n) inline
Definition at line 585 of file REAL.h.
References iRRAM::REAL::scale.
LAZY_BOOLEAN iRRAM::operator|| (const LAZY_BOOLEAN & x, const LAZY_BOOLEAN & y) noexcept
Definition at line 100 of file LAZY_BOOLEAN.cc.
template<class... PARAM> FUNCTION<LAZY_BOOLEAN,PARAM...> iRRAM::operator|| (const FUNCTION< LAZY_BOOLEAN, PARAM... > & a, const FUNCTION< LAZY_BOOLEAN, PARAM... > & b) inline
Definition at line 577 of file FUNCTION.h.
References juxtaposition(), and LAZY_BOOLEAN_FUNCTION_or().
template<class PARAM > FUNCTION<PARAM,PARAM> iRRAM::polynomial (const std::vector< PARAM > & coeff) inline
Definition at line 252 of file FUNCTION.h.
References from_algorithm().
LAZY_BOOLEAN iRRAM::positive (const REAL & x, int k)
Definition at line 571 of file REALS.cc.
References iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, MP_sign, iRRAM::REAL::positive, sizetype_less(), sizetype_power2(), iRRAM::REAL::value, and iRRAM::REAL::vsize.
Referenced by arg(), and exp().
INTERVAL iRRAM::power (const INTERVAL & x, int n)
Definition at line 136 of file INTERVAL.cc.
References abs(), iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), iRRAM::INTERVAL::power, iRRAM::INTERVAL::square, and iRRAM::INTERVAL::upp.
Referenced by ln2(), round(), and strtoREAL().
INTEGER iRRAM::power (const INTEGER & x, unsigned n) inline
Definition at line 219 of file INTEGER.h.
References MP_int_init, MP_int_power_i, and MP_int_type.
template<class RESULT1 , class... PARAM1, class RESULT2 , class... PARAM2> FUNCTION<std::pair<RESULT1,RESULT2>,std::pair<PARAM1...,PARAM2...> > iRRAM::product (const FUNCTION< RESULT1, PARAM1... > & f_1, const FUNCTION< RESULT2, PARAM2... > & f_2) inline
Definition at line 160 of file FUNCTION.h.
References from_algorithm().
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::projection (const FUNCTION< std::vector< RESULT >, PARAM... > & f, const int i) inline
Definition at line 234 of file FUNCTION.h.
References from_algorithm().
LAZY_BOOLEAN iRRAM::proper_subset (const INTERVAL & x, const INTERVAL & y)
Definition at line 323 of file INTERVAL.cc.
References iRRAM::INTERVAL::superset.
LAZY_BOOLEAN iRRAM::proper_superset (const INTERVAL & x, const INTERVAL & y)
Definition at line 317 of file INTERVAL.cc.
References iRRAM::INTERVAL::superset.
REAL iRRAM::real (const COMPLEX & z)
Definition at line 92 of file COMPLEX.cc.
References iRRAM::COMPLEX::_real.
void iRRAM::resources (double & time, unsigned int & memory)
Definition at line 64 of file REALmain.cc.
Referenced by ln2(), pi(), and show_statistics().
int iRRAM::round (const REAL & x) inline
Definition at line 368 of file REAL.h.
References iRRAM::REAL::abs, absolute, acos(), acosec(), acosech(), acosh(), acotan(), acoth(), iRRAM::REAL::as_INTEGER(), asec(), asech(), asin(), asinh(), atan(), atanh(), cos(), cosec(), cosech(), cosh(), cotan(), coth(), iRRAM::REAL::dp, iRRAM::REAL::error, euler(), exp(), ln2(), log(), maximum(), minimum(), modulo(), MP_getsize, MP_type, pi(), power(), iRRAM::REAL::REAL(), root(), rshow(), rwrite(), rwritee(), sec(), sech(), sin(), sinh(), iRRAM::REAL::sqrt, iRRAM::REAL::swrite, tan(), tanh(), iRRAM::REAL::value, and iRRAM::REAL::vsize.
REAL iRRAM::round2 (const REAL & x) inline
Definition at line 367 of file REAL.h.
References iRRAM::REAL::as_INTEGER(), and iRRAM::REAL::REAL().
Referenced by modulo().
REAL iRRAM::rowsumnorm (const REALMATRIX & x)
Definition at line 278 of file REALMATRIX.cc.
References abs(), iRRAM::REALMATRIX::maxcolumn, maximum(), and iRRAM::REALMATRIX::maxrow.
REAL iRRAM::rowsumnorm (const SPARSEREALMATRIX & x)
Definition at line 558 of file SPARSEREALMATRIX.cc.
References abs(), maximum(), iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPARSEREALMATRIX::rowvector, and iRRAM::SPM_ELEMENT::value.
void iRRAM::rshow (const REAL & x, const int w)
Definition at line 478 of file REALS.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, cout, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, max(), MP_abs, MP_getsize, MP_init, MP_mv_mul, MP_sign, MP_type, iRRAM::ITERATION_DATA::prec_policy, iRRAM::REAL::REAL(), show, sizetype_inc_one(), sizetype_less(), state, iRRAM::REAL::swrite, iRRAM::REAL::value, and iRRAM::REAL::vsize.
Referenced by round().
void iRRAM::rwrite (const REAL & x, const int w)
Definition at line 476 of file REALS.cc.
References absolute, cout, and iRRAM::REAL::swrite.
Referenced by round().
void iRRAM::rwritee (const REAL & x, const int w)
Definition at line 477 of file REALS.cc.
References cout, relative, and iRRAM::REAL::swrite.
Referenced by round().
DYADIC iRRAM::scale (const DYADIC & x, const int n)
Definition at line 96 of file DYADIC.cc.
References iRRAM::DYADIC::DYADIC(), MP_init, MP_shift, MP_type, and iRRAM::DYADIC::value.
Referenced by euler(), iteration(), log(), max(), root(), sizetype_add_one(), sizetype_add_wo_norm(), sizetype_dec(), sizetype_inc(), sizetype_inc2(), sizetype_inc_one(), sizetype_less(), sizetype_max(), and tan().
RATIONAL iRRAM::scale (RATIONAL x, int n)
Definition at line 149 of file RATIONAL.cc.
References MP_rat_shift.
INTEGER iRRAM::scale (const INTEGER & x, const int n) inline
Definition at line 193 of file INTEGER.h.
References MP_int_init, MP_int_shift, and MP_int_type.
REAL iRRAM::scale (const REAL & x, int n)
Definition at line 553 of file REALS.cc.
References iRRAM::REAL::geterror(), MP_init, MP_shift, MP_type, iRRAM::REAL::REAL(), iRRAM::REAL::scale, and iRRAM::REAL::value.
template<class RESULT1 , class RESULT2 , class... PARAM> FUNCTION<RESULT2,PARAM... > iRRAM::second (const FUNCTION< std::pair< RESULT1, RESULT2 >, PARAM... > & f) inline
Definition at line 204 of file FUNCTION.h.
References from_algorithm().
_SetRflags iRRAM::setRflags (float_form n) inline
Definition at line 48 of file STREAMS.h.
References iRRAM::_SetRflags::_M_n.
_SetRwidth iRRAM::setRwidth (int __n) inline
Definition at line 40 of file STREAMS.h.
References iRRAM::_SetRwidth::_M_n.
void iRRAM::show_statistics ()
Definition at line 79 of file REALmain.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, cerr, ln2_time, iRRAM::state_t::max_prec, MP_var_count, mpfr_TotalAllocVarCount, mpfr_TotalFreedVarCount, pi_time, iRRAM::ITERATION_DATA::prec_step, resources(), and state.
Referenced by exec().
int iRRAM::sign (const INTEGER & x) inline
Definition at line 206 of file INTEGER.h.
References MP_int_sign.
INTERVAL iRRAM::sin (const INTERVAL & x)
Definition at line 158 of file INTERVAL.cc.
References choose(), iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), modulo(), pi(), iRRAM::INTERVAL::sin, and iRRAM::INTERVAL::upp.
int iRRAM::size (const DYADIC & x)
Definition at line 131 of file DYADIC.cc.
References MP_min, MP_size, and iRRAM::DYADIC::value.
Referenced by csqrt(), log(), maxnorm(), operator+(), operator-(), iRRAM::REALMATRIX::operator=(), iRRAM::REALMATRIX::REALMATRIX(), root(), and tan().
int iRRAM::size (const INTEGER & x) inline
Definition at line 213 of file INTEGER.h.
References MP_int_size.
int iRRAM::size (const REAL & x)
Returns a tight bound to the logarithmic value of |x|: \(2^{k-2}-2^e\leq|x|<2^k\), where e is x.vsize.exponent.
This is a multi-valued function.
For \(\hat x=m\cdot2^e\) = x.vsize and \(x_\varepsilon\) = x.error, this function computes \(k=\lceil\log_2(\hat x+x_\varepsilon)\rceil>\log_2|x|\) and via reiteration enforces that \(\hat x\geq x_\varepsilon+2^{k-2}\) which is equivalent to \(2^{k-2}\leq\hat x-x_\varepsilon=(m-1)\cdot2^e-x_\varepsilon+2^e \leq|x|+2^e\), the guarrantee therefore is \(2^{k-2}-2^e\leq|x|<2^k\).
Parameters
x non-zero real number
Returns
\(k\in\mathbb Z:2^{k-2}-2^e\leq|x|<2^k\), where e is x.vsize.exponent and min_exponent <= k < MP_max
Exceptions
iRRAM_Numerical_Exception(iRRAM_underflow_error) if x is exact with value zero. If x is not exact but zero, reiterations will be performed.
See also
REITERATE
Todo:
According to documentation, size(const REAL &) should compute \(\begin{cases} 1+\lfloor\log_2|x|\rfloor\text,&x\neq 0 \\ 1+\lceil\log_2|x|\rceil\text,&x\neq 0 \\ \text{undef,}&x=0 \end{cases}\) but it does compute \(\begin{cases} i+\lfloor\log_2|x|\rfloor\text,&x\neq 0, i\in\{1,2,3\} \\ \text{undef,}&x=0 \end{cases}\)
Definition at line 666 of file REALS.cc.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::iRRAM_thread_data_class::cache_i, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::iRRAM_cache< DATA >::put(), iRRAM::REAL::REAL(), REITERATE, iRRAM::REAL::size, sizetype_add_power2(), sizetype_less(), sizetype_log2(), state, iRRAM::state_t::thread_data_address, iRRAM::REAL::value, and iRRAM::REAL::vsize.
REALMATRIX iRRAM::solve (REALMATRIX & lside, REALMATRIX & rside, int use_pivot)
Definition at line 132 of file REALMATRIX.cc.
References ELEMENT, iRRAM::REALMATRIX::maxcolumn, iRRAM::REALMATRIX::maxrow, and upperbound().
SPARSEREALMATRIX iRRAM::solve (SPARSEREALMATRIX & lside, SPARSEREALMATRIX & rside, int use_pivot)
Definition at line 460 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::colvector, iRRAM::SPARSEREALMATRIX::maxcolumn, iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPM_ELEMENT::rowindex, iRRAM::SPARSEREALMATRIX::rowvector, iRRAM::SPARSEREALMATRIX::sparse_get_ptr, iRRAM::SPARSEREALMATRIX::sparse_set, upperbound(), and iRRAM::SPM_ELEMENT::value.
SPARSEREALMATRIX iRRAM::sparse_eye (unsigned int rows)
Definition at line 181 of file SPARSEREALMATRIX.cc.
References iRRAM::SPARSEREALMATRIX::colvector, iRRAM::SPARSEREALMATRIX::filled, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPARSEREALMATRIX::rows, and iRRAM::SPARSEREALMATRIX::rowvector.
SPM_ELEMENT* iRRAM::sparse_get_ptr (SPARSEREALMATRIX & m, unsigned int i, unsigned int j)
Definition at line 135 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::hotspot, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::rowindex, and iRRAM::SPARSEREALMATRIX::rowvector.
Referenced by equilib_del().
SPARSEREALMATRIX iRRAM::sparse_ones (unsigned int rows, unsigned int columns)
Definition at line 202 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::columns, iRRAM::SPARSEREALMATRIX::colvector, iRRAM::SPARSEREALMATRIX::filled, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPM_ELEMENT::rowindex, iRRAM::SPARSEREALMATRIX::rows, iRRAM::SPARSEREALMATRIX::rowvector, and iRRAM::SPM_ELEMENT::value.
void iRRAM::sparse_set (SPARSEREALMATRIX & m, unsigned int i, unsigned int j, const REAL & x)
Definition at line 32 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::colvector, iRRAM::SPARSEREALMATRIX::filled, iRRAM::SPARSEREALMATRIX::hotspot, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPM_ELEMENT::rowindex, iRRAM::SPARSEREALMATRIX::rowvector, and iRRAM::SPM_ELEMENT::value.
Referenced by equilib_del(), and steady_state().
void iRRAM::sparse_unset (SPARSEREALMATRIX & m, unsigned int i, unsigned int j)
Definition at line 73 of file SPARSEREALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::SPARSEREALMATRIX::colvector, iRRAM::SPARSEREALMATRIX::filled, iRRAM::SPARSEREALMATRIX::hotspot, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPM_ELEMENT::rowindex, and iRRAM::SPARSEREALMATRIX::rowvector.
SPARSEREALMATRIX iRRAM::sparse_zeroes (unsigned int rows, unsigned int columns)
Definition at line 196 of file SPARSEREALMATRIX.cc.
INTERVAL iRRAM::square (const INTERVAL & x)
Definition at line 131 of file INTERVAL.cc.
References abs(), iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, maximum(), minimum(), iRRAM::INTERVAL::square, and iRRAM::INTERVAL::upp.
REAL iRRAM::square (const REAL & x) inline
Definition at line 778 of file REAL.h.
References iRRAM::REAL::dp, iRRAM_unlikely, iRRAM::REAL::REAL(), and iRRAM::REAL::value.
REALMATRIX iRRAM::steady_state (const REALMATRIX & x)
Definition at line 334 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::columns, and iRRAM::REALMATRIX::rows.
Referenced by iRRAM::REALMATRIX::seterror().
REALMATRIX iRRAM::steady_state (const SPARSEREALMATRIX & x)
Definition at line 370 of file REALMATRIX.cc.
References iRRAM::SPM_ELEMENT::colindex, iRRAM::REALMATRIX::columns, iRRAM::SPARSEREALMATRIX::colvector, cout, iRRAM::SPARSEREALMATRIX::filled, iRRAM::SPARSEREALMATRIX::maxrow, iRRAM::SPM_ELEMENT::nextcol, iRRAM::SPM_ELEMENT::nextrow, iRRAM::SPM_ELEMENT::rowindex, iRRAM::REALMATRIX::rows, iRRAM::SPARSEREALMATRIX::rowvector, sparse_set(), and iRRAM::SPM_ELEMENT::value.
REAL iRRAM::strtoREAL (const char * s, char ** endptr)
Definition at line 990 of file REALS.cc.
References exp(), power(), iRRAM::REAL::REAL(), and sign().
Referenced by atoREAL(), and iRRAM::REAL::seterror().
REAL iRRAM::strtoREAL2 (const char * s, char ** endptr)
Converts a base-10 string in scientific notation to REAL.
If \(p\) is the current working precision of iRRAM, \(k\) the number of digits in the integer part, \(z\) the number of leading zero-digits (including the fractional part) and \(g\) the exponent, and the represented value is not zero, then the result has a relative precision of roughly \((g+k-z)\log_2(10)-p\) bits, which corresponds to an absolute accuracy of \(2^p\).
Parameters
[in] s pointer to base-10 string; format: WSDFE where
W = optional whitespace; it is discarded
S = optional sign
D = optional string of digits 0..9
F = optional: . followed by optional string of digits 0..9
E = optional: e or E followed by an optional sign followed by a string of digits 0..9
DF must be non-empty and not just contain .
[out] endptr when non-NULL, the pointer to the end of the represented number is stored in *endptr
Returns
a REAL object accurate to the current working precision.
Proof
The precision depends only on DF and E; let \(x_k\ldots x_{-n}=DF[1..|F|]\) and \(z\in\mathbb N:x[1..z]=\texttt 0^z\). To represent zero up to any accuracy, only 1 bit is required. So let \(x\neq0\) and \(b\cdot2^c\) with \(b\in[2^{-1};1)\) be the result. Then the error is
\[ (*)=|10^g\sum_{i=-n}^{k-z} x_i\cdot 10^i-2^cb| =|2^{\overbrace{(g+k-z+1)\log_2(10)}^{=:q}} \underbrace{\sum_{i=-n-(k-z+1)}^{-1}x_{i+k-z+1}\cdot10^i}_{=:x'\in[10^{-1};1)} -2^cb| \]
Now, MPFR's mpfr_strtofr() guarantees for the exact input \(2^qx'=:2^{\overline q}\overline b\) with \(\overline b\in[2^{-1};1)\) that the error is \(|2^{\overline q}\overline b-2^cb|<2^{\overline q-m}\), therefore
\[(*)=|2^qx'-2^{\overline q}\overline b+2^{\overline q}\overline b-2^cb| <|2^qx'-2^{\overline q}\overline b|+2^{\overline q-m}=2^{\overline q-m} \]
Since \(2^{\overline q}/2\leq 2^{\overline q}\overline b=2^qx'<2^q\), the error is bounded, \((*)<2^p\), when \(\overline q-p<m\leq q+1-p<\lceil(g+k-z+1)\log_2(10)\rceil+1-p\leq m'\). The exact precision is \(\max(10,m')\) where \(m'=1+\begin{cases} 1&z=k+n+1\\ \lfloor((g+k-z+1)\cdot 10+2)/3+1\rfloor-p&\text{otherwise} \end{cases}\)
Definition at line 937 of file REALS.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, ext_mpfr_remove_trailing_zeroes(), iRRAM_DEBUG2, max(), MP_init, MP_type, iRRAM::REAL::REAL(), sizetype_exact(), sizetype_power2(), state, and iRRAM::REAL::value.
DYADIC iRRAM::SUB (const DYADIC & x, const DYADIC & y, const int p)
Definition at line 73 of file DYADIC.cc.
References MP_init, MP_sub, MP_type, and iRRAM::DYADIC::value.
LAZY_BOOLEAN iRRAM::subset (const INTERVAL & x, const INTERVAL & y)
Definition at line 320 of file INTERVAL.cc.
References iRRAM::INTERVAL::superset.
template<class RESULT , class... PARAM> FUNCTION<RESULT,PARAM...> iRRAM::subtraction (const FUNCTION< std::pair< RESULT, RESULT >, PARAM... > & a) inline
Definition at line 303 of file FUNCTION.h.
References from_algorithm().
Referenced by operator-().
REAL iRRAM::sup (const INTERVAL & x)
Definition at line 110 of file INTERVAL.cc.
References iRRAM::INTERVAL::upp.
LAZY_BOOLEAN iRRAM::superset (const INTERVAL & x, const INTERVAL & y)
Definition at line 311 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
void iRRAM::swap (REAL & a, REAL & b) inline noexcept
Definition at line 539 of file REAL.h.
References iRRAM::REAL::swap.
Referenced by iRRAM::wrap_type< T, clearfct >::operator=(), iRRAM::DYADIC::operator=(), iRRAM::RATIONAL::operator=(), iRRAM::INTEGER::operator=(), iRRAM::REAL::operator=(), and iRRAM::wrap_type< T, clearfct >::wrap_type().
std::string iRRAM::swrite (const DYADIC & x, const int w)
Definition at line 122 of file DYADIC.cc.
References MP_swrite, and iRRAM::DYADIC::value.
Referenced by iRRAM::orstream::operator<<().
std::string iRRAM::swrite (const REAL & x, const int w, const float_form form)
Definition at line 199 of file REALS.cc.
References absolute, iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::iRRAM_thread_data_class::cache_s, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), GUARD_BITS, iRRAM::ITERATION_DATA::inlimit, iRRAM_DEBUG2, iRRAM::generic_sizetype< M, E >::mantissa, max(), MP_getsize, MP_init, MP_mv_div, MP_mv_divi, MP_mv_isub, MP_mv_mul, MP_mv_muli, MP_mv_sub, MP_mv_subi, MP_size, MP_swrite, MP_type, iRRAM::ITERATION_DATA::prec_policy, iRRAM::iRRAM_cache< DATA >::put(), iRRAM::REAL::REAL(), REITERATE, relative, show, iRRAM::REAL::size, sizetype_add_one(), sizetype_add_wo_norm(), sizetype_dec(), sizetype_div(), sizetype_half(), sizetype_inc_one(), sizetype_less(), sizetype_normalize(), sizetype_power2(), state, iRRAM::REAL::swrite, iRRAM::state_t::thread_data_address, iRRAM::REAL::value, and iRRAM::REAL::vsize.
std::string iRRAM::swrite (const RATIONAL & x, const int w)
Definition at line 285 of file RATIONAL.cc.
References MP_rat_swritee.
std::string iRRAM::swrite (const RATIONAL & x)
Definition at line 297 of file RATIONAL.cc.
References MP_rat_sprintf.
std::string iRRAM::swrite (const INTEGER & x, const int w) inline
Definition at line 506 of file INTEGER.h.
References MP_int_swritee.
std::string iRRAM::swrite (const INTEGER & x) inline
Definition at line 519 of file INTEGER.h.
References MP_int_sprintf.
INTERVAL iRRAM::tan (const INTERVAL & x)
Definition at line 285 of file INTERVAL.cc.
References iRRAM::INTERVAL::INTERVAL(), iRRAM::INTERVAL::low, iRRAM::INTERVAL::tan, and iRRAM::INTERVAL::upp.
int iRRAM::upperbound (const REAL & x)
Definition at line 696 of file REALS.cc.
References iRRAM::state_t::ACTUAL_STACK, iRRAM::iRRAM_thread_data_class::cache_i, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::iRRAM_cache< DATA >::get(), iRRAM::ITERATION_DATA::inlimit, iRRAM::generic_sizetype< M, E >::mantissa, iRRAM::iRRAM_cache< DATA >::put(), sizetype_add(), state, iRRAM::state_t::thread_data_address, iRRAM::REAL::upperbound, iRRAM::REAL::value, and iRRAM::REAL::vsize.
Referenced by solve().
REAL iRRAM::wid (const INTERVAL & x)
Definition at line 102 of file INTERVAL.cc.
References iRRAM::INTERVAL::low, and iRRAM::INTERVAL::upp.
REALMATRIX iRRAM::zeroes (unsigned int rows, unsigned int columns)
Definition at line 54 of file REALMATRIX.cc.
References iRRAM::REALMATRIX::columns, ELEMENT, and iRRAM::REALMATRIX::rows.
Variable Documentation
orstream cerr & iRRAM::std::cerr
Definition at line 39 of file STREAMS.cc.
Referenced by exec(), iRRAM_initialize2(), limit(), limit_debug(), limit_debug2(), iRRAM::REAL::rcheck(), and show_statistics().
irstream iRRAM::cin
Definition at line 42 of file STREAMS.cc.
Referenced by iRRAM::irstream::irstream(), and iRRAM::irstream::~irstream().
orstream clog & iRRAM::std::clog
Definition at line 40 of file STREAMS.cc.
orstream iRRAM::cout
Definition at line 41 of file STREAMS.cc.
Referenced by equilib_del(), exec(), iRRAM::orstream::orstream(), rshow(), rwrite(), rwritee(), steady_state(), and iRRAM::orstream::~orstream().
const int *const iRRAM::iRRAM_prec_array = _iRRAM_prec_array
Definition at line 77 of file REALmain.cc.
Referenced by iRRAM_initialize2(), limit(), limit_hint(), and limit_mv().
const int iRRAM::iRRAM_prec_steps =512
Definition at line 75 of file REALmain.cc.
Referenced by iRRAM_initialize2().
double iRRAM::ln2_time = 0.0
Definition at line 16 of file pi_ln2.cc.
Referenced by show_statistics().
double iRRAM::pi_time = 0.0
Definition at line 17 of file pi_ln2.cc.
Referenced by show_statistics().
iRRAM_TLS state_t iRRAM::state
Definition at line 46 of file stack.cc.
Referenced by iRRAM::iRRAM_cache< MP_int_type >::activate(), approx(), iRRAM::REAL::as_INTEGER(), iRRAM::orstream::bad(), iRRAM::irstream::bad(), check(), choose(), iRRAM::DYADIC_precision::DYADIC_precision(), iRRAM::orstream::eof(), iRRAM::irstream::eof(), euler(), exec(), iRRAM::orstream::fail(), iRRAM::irstream::fail(), iRRAM::DYADIC::getprec(), iRRAM::orstream::good(), iRRAM::irstream::good(), iRRAM::stiff::inc_step(), iRRAM_initialize2(), iRRAM::irstream::irstream(), iteration(), limit(), limit_debug(), limit_debug2(), limit_lip(), limit_mv(), lipschitz(), lipschitz_1p_1a(), ln2(), module(), iRRAM::LAZY_BOOLEAN::operator bool(), iRRAM::orstream::operator bool(), iRRAM::irstream::operator bool(), operator!(), iRRAM::REAL::operator=(), iRRAM::irstream::operator>>(), iRRAM::orstream::orstream(), pi(), iRRAM::precision_mode::precision_mode(), iRRAM::REAL::REAL(), iRRAM::orstream::reset(), iRRAM::orstream::rewind(), rshow(), iRRAM::stiff::set_prec_step(), show_statistics(), iRRAM::single_valued::single_valued(), size(), sqrt(), strtoREAL2(), swrite(), upperbound(), iRRAM::DYADIC_precision::~DYADIC_precision(), iRRAM::irstream::~irstream(), iRRAM::orstream::~orstream(), iRRAM::precision_mode::~precision_mode(), and iRRAM::single_valued::~single_valued().