iRRAM: src/REALmain.cc File Reference
REALmain.cc File Reference
#include <cmath>
#include <cstdlib>
#include <cstdarg>
#include <cstring>
#include <vector>
#include <iRRAM/lib.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <unistd.h>
Namespaces
iRRAM
Functions
void iRRAM::resources (double &time, unsigned int &memory)
void iRRAM::show_statistics ()
int iRRAM_exec (void(*f)(void *), void *data)
void iRRAM_initialize2 (int *argc, char **argv)
like iRRAM_initialize(), but modifies its arguments as to remove parsed options pertaining iRRAM.
void iRRAM_initialize (int argc, char **argv)
Variables
const int iRRAM::iRRAM_prec_steps =512
const int *const iRRAM::iRRAM_prec_array = _iRRAM_prec_array
Function Documentation
iRRAM_exec()
int iRRAM_exec (void(*)(void *) f, void * data)
Definition at line 109 of file REALmain.cc.
References iRRAM::exec(), and iRRAM::iRRAM_Numerical_Exception::type.
iRRAM_initialize()
void iRRAM_initialize (int argc, char ** argv)
Definition at line 221 of file REALmain.cc.
References iRRAM_initialize2().
iRRAM_initialize2()
void iRRAM_initialize2 (int * argc, char ** argv)
like iRRAM_initialize(), but modifies its arguments as to remove parsed options pertaining iRRAM.
Definition at line 119 of file REALmain.cc.
References iRRAM::state_t::debug, iRRAM_DEBUG1, iRRAM_DEBUG2, MP_initialize, iRRAM::state_t::prec_skip, iRRAM::state_t::prec_start, and iRRAM::state.
Referenced by iRRAM_initialize(), and main().